// Code generated by mockery. DO NOT EDIT.

package clienttest

import (
	context "context"

	client "github.com/fromforgesoftware/aegis/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// AuthorizerAPI is an autogenerated mock type for the AuthorizerAPI type
type AuthorizerAPI struct {
	mock.Mock
}

type AuthorizerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizerAPI) EXPECT() *AuthorizerAPI_Expecter {
	return &AuthorizerAPI_Expecter{mock: &_m.Mock}
}

// BatchCheck provides a mock function with given fields: ctx, batch
func (_m *AuthorizerAPI) BatchCheck(ctx context.Context, batch client.BatchCheck) ([]client.PermissionDecision, error) {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for BatchCheck")
	}

	var r0 []client.PermissionDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.BatchCheck) ([]client.PermissionDecision, error)); ok {
		return rf(ctx, batch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.BatchCheck) []client.PermissionDecision); ok {
		r0 = rf(ctx, batch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PermissionDecision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.BatchCheck) error); ok {
		r1 = rf(ctx, batch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizerAPI_BatchCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCheck'
type AuthorizerAPI_BatchCheck_Call struct {
	*mock.Call
}

// BatchCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - batch client.BatchCheck
func (_e *AuthorizerAPI_Expecter) BatchCheck(ctx interface{}, batch interface{}) *AuthorizerAPI_BatchCheck_Call {
	return &AuthorizerAPI_BatchCheck_Call{Call: _e.mock.On("BatchCheck", ctx, batch)}
}

func (_c *AuthorizerAPI_BatchCheck_Call) Run(run func(ctx context.Context, batch client.BatchCheck)) *AuthorizerAPI_BatchCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.BatchCheck))
	})
	return _c
}

func (_c *AuthorizerAPI_BatchCheck_Call) Return(_a0 []client.PermissionDecision, _a1 error) *AuthorizerAPI_BatchCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizerAPI_BatchCheck_Call) RunAndReturn(run func(context.Context, client.BatchCheck) ([]client.PermissionDecision, error)) *AuthorizerAPI_BatchCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function with given fields: ctx, check
func (_m *AuthorizerAPI) Check(ctx context.Context, check client.Check) (bool, error) {
	ret := _m.Called(ctx, check)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Check) (bool, error)); ok {
		return rf(ctx, check)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Check) bool); ok {
		r0 = rf(ctx, check)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Check) error); ok {
		r1 = rf(ctx, check)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizerAPI_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type AuthorizerAPI_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - check client.Check
func (_e *AuthorizerAPI_Expecter) Check(ctx interface{}, check interface{}) *AuthorizerAPI_Check_Call {
	return &AuthorizerAPI_Check_Call{Call: _e.mock.On("Check", ctx, check)}
}

func (_c *AuthorizerAPI_Check_Call) Run(run func(ctx context.Context, check client.Check)) *AuthorizerAPI_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Check))
	})
	return _c
}

func (_c *AuthorizerAPI_Check_Call) Return(_a0 bool, _a1 error) *AuthorizerAPI_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizerAPI_Check_Call) RunAndReturn(run func(context.Context, client.Check) (bool, error)) *AuthorizerAPI_Check_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessible provides a mock function with given fields: ctx, list
func (_m *AuthorizerAPI) ListAccessible(ctx context.Context, list client.ListAccessible) ([]string, error) {
	ret := _m.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessible")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ListAccessible) ([]string, error)); ok {
		return rf(ctx, list)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.ListAccessible) []string); ok {
		r0 = rf(ctx, list)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.ListAccessible) error); ok {
		r1 = rf(ctx, list)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizerAPI_ListAccessible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessible'
type AuthorizerAPI_ListAccessible_Call struct {
	*mock.Call
}

// ListAccessible is a helper method to define mock.On call
//   - ctx context.Context
//   - list client.ListAccessible
func (_e *AuthorizerAPI_Expecter) ListAccessible(ctx interface{}, list interface{}) *AuthorizerAPI_ListAccessible_Call {
	return &AuthorizerAPI_ListAccessible_Call{Call: _e.mock.On("ListAccessible", ctx, list)}
}

func (_c *AuthorizerAPI_ListAccessible_Call) Run(run func(ctx context.Context, list client.ListAccessible)) *AuthorizerAPI_ListAccessible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.ListAccessible))
	})
	return _c
}

func (_c *AuthorizerAPI_ListAccessible_Call) Return(_a0 []string, _a1 error) *AuthorizerAPI_ListAccessible_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizerAPI_ListAccessible_Call) RunAndReturn(run func(context.Context, client.ListAccessible) ([]string, error)) *AuthorizerAPI_ListAccessible_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields: ctx
func (_m *AuthorizerAPI) Version(ctx context.Context) (client.AuthzVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 client.AuthzVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.AuthzVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.AuthzVersion); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.AuthzVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizerAPI_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type AuthorizerAPI_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthorizerAPI_Expecter) Version(ctx interface{}) *AuthorizerAPI_Version_Call {
	return &AuthorizerAPI_Version_Call{Call: _e.mock.On("Version", ctx)}
}

func (_c *AuthorizerAPI_Version_Call) Run(run func(ctx context.Context)) *AuthorizerAPI_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthorizerAPI_Version_Call) Return(_a0 client.AuthzVersion, _a1 error) *AuthorizerAPI_Version_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizerAPI_Version_Call) RunAndReturn(run func(context.Context) (client.AuthzVersion, error)) *AuthorizerAPI_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizerAPI creates a new instance of AuthorizerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizerAPI {
	mock := &AuthorizerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
