// Code generated by mockery. DO NOT EDIT.

package clienttest

import (
	context "context"

	client "github.com/fromforgesoftware/aegis/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// ResourceAPI is an autogenerated mock type for the ResourceAPI type
type ResourceAPI struct {
	mock.Mock
}

type ResourceAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceAPI) EXPECT() *ResourceAPI_Expecter {
	return &ResourceAPI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, resource
func (_m *ResourceAPI) Create(ctx context.Context, resource client.Resource) (client.Resource, error) {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 client.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Resource) (client.Resource, error)); ok {
		return rf(ctx, resource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Resource) client.Resource); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Get(0).(client.Resource)
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Resource) error); ok {
		r1 = rf(ctx, resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceAPI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResourceAPI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - resource client.Resource
func (_e *ResourceAPI_Expecter) Create(ctx interface{}, resource interface{}) *ResourceAPI_Create_Call {
	return &ResourceAPI_Create_Call{Call: _e.mock.On("Create", ctx, resource)}
}

func (_c *ResourceAPI_Create_Call) Run(run func(ctx context.Context, resource client.Resource)) *ResourceAPI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Resource))
	})
	return _c
}

func (_c *ResourceAPI_Create_Call) Return(_a0 client.Resource, _a1 error) *ResourceAPI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceAPI_Create_Call) RunAndReturn(run func(context.Context, client.Resource) (client.Resource, error)) *ResourceAPI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ResourceAPI) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceAPI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ResourceAPI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceAPI_Expecter) Delete(ctx interface{}, id interface{}) *ResourceAPI_Delete_Call {
	return &ResourceAPI_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ResourceAPI_Delete_Call) Run(run func(ctx context.Context, id string)) *ResourceAPI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResourceAPI_Delete_Call) Return(_a0 error) *ResourceAPI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceAPI_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ResourceAPI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *ResourceAPI) Get(ctx context.Context, id string) (client.Resource, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.Resource, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.Resource); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(client.Resource)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceAPI_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ResourceAPI_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ResourceAPI_Expecter) Get(ctx interface{}, id interface{}) *ResourceAPI_Get_Call {
	return &ResourceAPI_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *ResourceAPI_Get_Call) Run(run func(ctx context.Context, id string)) *ResourceAPI_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResourceAPI_Get_Call) Return(_a0 client.Resource, _a1 error) *ResourceAPI_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceAPI_Get_Call) RunAndReturn(run func(context.Context, string) (client.Resource, error)) *ResourceAPI_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *ResourceAPI) List(ctx context.Context, opts ...client.ListOption) ([]client.Resource, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []client.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...client.ListOption) ([]client.Resource, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...client.ListOption) []client.Resource); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...client.ListOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceAPI_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ResourceAPI_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...client.ListOption
func (_e *ResourceAPI_Expecter) List(ctx interface{}, opts ...interface{}) *ResourceAPI_List_Call {
	return &ResourceAPI_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *ResourceAPI_List_Call) Run(run func(ctx context.Context, opts ...client.ListOption)) *ResourceAPI_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(client.ListOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ResourceAPI_List_Call) Return(_a0 []client.Resource, _a1 error) *ResourceAPI_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceAPI_List_Call) RunAndReturn(run func(context.Context, ...client.ListOption) ([]client.Resource, error)) *ResourceAPI_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceAPI creates a new instance of ResourceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceAPI {
	mock := &ResourceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
