// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	mock "github.com/stretchr/testify/mock"
)

// AccountMergeRepository is an autogenerated mock type for the AccountMergeRepository type
type AccountMergeRepository struct {
	mock.Mock
}

type AccountMergeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountMergeRepository) EXPECT() *AccountMergeRepository_Expecter {
	return &AccountMergeRepository_Expecter{mock: &_m.Mock}
}

// RecordMergeEvent provides a mock function with given fields: ctx, e
func (_m *AccountMergeRepository) RecordMergeEvent(ctx context.Context, e app.AccountMergeEvent) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for RecordMergeEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, app.AccountMergeEvent) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountMergeRepository_RecordMergeEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordMergeEvent'
type AccountMergeRepository_RecordMergeEvent_Call struct {
	*mock.Call
}

// RecordMergeEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - e app.AccountMergeEvent
func (_e *AccountMergeRepository_Expecter) RecordMergeEvent(ctx interface{}, e interface{}) *AccountMergeRepository_RecordMergeEvent_Call {
	return &AccountMergeRepository_RecordMergeEvent_Call{Call: _e.mock.On("RecordMergeEvent", ctx, e)}
}

func (_c *AccountMergeRepository_RecordMergeEvent_Call) Run(run func(ctx context.Context, e app.AccountMergeEvent)) *AccountMergeRepository_RecordMergeEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.AccountMergeEvent))
	})
	return _c
}

func (_c *AccountMergeRepository_RecordMergeEvent_Call) Return(_a0 error) *AccountMergeRepository_RecordMergeEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountMergeRepository_RecordMergeEvent_Call) RunAndReturn(run func(context.Context, app.AccountMergeEvent) error) *AccountMergeRepository_RecordMergeEvent_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteSource provides a mock function with given fields: ctx, source
func (_m *AccountMergeRepository) SoftDeleteSource(ctx context.Context, source string) error {
	ret := _m.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteSource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountMergeRepository_SoftDeleteSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteSource'
type AccountMergeRepository_SoftDeleteSource_Call struct {
	*mock.Call
}

// SoftDeleteSource is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
func (_e *AccountMergeRepository_Expecter) SoftDeleteSource(ctx interface{}, source interface{}) *AccountMergeRepository_SoftDeleteSource_Call {
	return &AccountMergeRepository_SoftDeleteSource_Call{Call: _e.mock.On("SoftDeleteSource", ctx, source)}
}

func (_c *AccountMergeRepository_SoftDeleteSource_Call) Run(run func(ctx context.Context, source string)) *AccountMergeRepository_SoftDeleteSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountMergeRepository_SoftDeleteSource_Call) Return(_a0 error) *AccountMergeRepository_SoftDeleteSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountMergeRepository_SoftDeleteSource_Call) RunAndReturn(run func(context.Context, string) error) *AccountMergeRepository_SoftDeleteSource_Call {
	_c.Call.Return(run)
	return _c
}

// TransferBindings provides a mock function with given fields: ctx, source, target
func (_m *AccountMergeRepository) TransferBindings(ctx context.Context, source string, target string) (int64, error) {
	ret := _m.Called(ctx, source, target)

	if len(ret) == 0 {
		panic("no return value specified for TransferBindings")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, source, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, source, target)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountMergeRepository_TransferBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferBindings'
type AccountMergeRepository_TransferBindings_Call struct {
	*mock.Call
}

// TransferBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - target string
func (_e *AccountMergeRepository_Expecter) TransferBindings(ctx interface{}, source interface{}, target interface{}) *AccountMergeRepository_TransferBindings_Call {
	return &AccountMergeRepository_TransferBindings_Call{Call: _e.mock.On("TransferBindings", ctx, source, target)}
}

func (_c *AccountMergeRepository_TransferBindings_Call) Run(run func(ctx context.Context, source string, target string)) *AccountMergeRepository_TransferBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AccountMergeRepository_TransferBindings_Call) Return(_a0 int64, _a1 error) *AccountMergeRepository_TransferBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountMergeRepository_TransferBindings_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *AccountMergeRepository_TransferBindings_Call {
	_c.Call.Return(run)
	return _c
}

// TransferExternalIDs provides a mock function with given fields: ctx, source, target
func (_m *AccountMergeRepository) TransferExternalIDs(ctx context.Context, source string, target string) (int64, error) {
	ret := _m.Called(ctx, source, target)

	if len(ret) == 0 {
		panic("no return value specified for TransferExternalIDs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, source, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, source, target)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountMergeRepository_TransferExternalIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferExternalIDs'
type AccountMergeRepository_TransferExternalIDs_Call struct {
	*mock.Call
}

// TransferExternalIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - target string
func (_e *AccountMergeRepository_Expecter) TransferExternalIDs(ctx interface{}, source interface{}, target interface{}) *AccountMergeRepository_TransferExternalIDs_Call {
	return &AccountMergeRepository_TransferExternalIDs_Call{Call: _e.mock.On("TransferExternalIDs", ctx, source, target)}
}

func (_c *AccountMergeRepository_TransferExternalIDs_Call) Run(run func(ctx context.Context, source string, target string)) *AccountMergeRepository_TransferExternalIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AccountMergeRepository_TransferExternalIDs_Call) Return(_a0 int64, _a1 error) *AccountMergeRepository_TransferExternalIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountMergeRepository_TransferExternalIDs_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *AccountMergeRepository_TransferExternalIDs_Call {
	_c.Call.Return(run)
	return _c
}

// TransferMemberships provides a mock function with given fields: ctx, source, target
func (_m *AccountMergeRepository) TransferMemberships(ctx context.Context, source string, target string) (int64, error) {
	ret := _m.Called(ctx, source, target)

	if len(ret) == 0 {
		panic("no return value specified for TransferMemberships")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, source, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, source, target)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountMergeRepository_TransferMemberships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferMemberships'
type AccountMergeRepository_TransferMemberships_Call struct {
	*mock.Call
}

// TransferMemberships is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - target string
func (_e *AccountMergeRepository_Expecter) TransferMemberships(ctx interface{}, source interface{}, target interface{}) *AccountMergeRepository_TransferMemberships_Call {
	return &AccountMergeRepository_TransferMemberships_Call{Call: _e.mock.On("TransferMemberships", ctx, source, target)}
}

func (_c *AccountMergeRepository_TransferMemberships_Call) Run(run func(ctx context.Context, source string, target string)) *AccountMergeRepository_TransferMemberships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AccountMergeRepository_TransferMemberships_Call) Return(_a0 int64, _a1 error) *AccountMergeRepository_TransferMemberships_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountMergeRepository_TransferMemberships_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *AccountMergeRepository_TransferMemberships_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountMergeRepository creates a new instance of AccountMergeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountMergeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountMergeRepository {
	mock := &AccountMergeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
