// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// AuditEventReader is an autogenerated mock type for the AuditEventReader type
type AuditEventReader struct {
	mock.Mock
}

type AuditEventReader_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventReader) EXPECT() *AuditEventReader_Expecter {
	return &AuditEventReader_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, opts
func (_m *AuditEventReader) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.AuditEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.AuditEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.AuditEvent]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.AuditEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventReader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditEventReader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *AuditEventReader_Expecter) List(ctx interface{}, opts ...interface{}) *AuditEventReader_List_Call {
	return &AuditEventReader_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuditEventReader_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *AuditEventReader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuditEventReader_List_Call) Return(_a0 resource.ListResponse[domain.AuditEvent], _a1 error) *AuditEventReader_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventReader_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)) *AuditEventReader_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventReader creates a new instance of AuditEventReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventReader {
	mock := &AuditEventReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
