// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Auditor is an autogenerated mock type for the Auditor type
type Auditor struct {
	mock.Mock
}

type Auditor_Expecter struct {
	mock *mock.Mock
}

func (_m *Auditor) EXPECT() *Auditor_Expecter {
	return &Auditor_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, action, resourceType, resourceID, changes
func (_m *Auditor) Record(ctx context.Context, action string, resourceType string, resourceID string, changes map[string]interface{}) {
	_m.Called(ctx, action, resourceType, resourceID, changes)
}

// Auditor_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type Auditor_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - action string
//   - resourceType string
//   - resourceID string
//   - changes map[string]interface{}
func (_e *Auditor_Expecter) Record(ctx interface{}, action interface{}, resourceType interface{}, resourceID interface{}, changes interface{}) *Auditor_Record_Call {
	return &Auditor_Record_Call{Call: _e.mock.On("Record", ctx, action, resourceType, resourceID, changes)}
}

func (_c *Auditor_Record_Call) Run(run func(ctx context.Context, action string, resourceType string, resourceID string, changes map[string]interface{})) *Auditor_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *Auditor_Record_Call) Return() *Auditor_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *Auditor_Record_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]interface{})) *Auditor_Record_Call {
	_c.Run(run)
	return _c
}

// NewAuditor creates a new instance of Auditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auditor {
	mock := &Auditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
