// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthorizationUsecase is an autogenerated mock type for the AuthorizationUsecase type
type AuthorizationUsecase struct {
	mock.Mock
}

type AuthorizationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationUsecase) EXPECT() *AuthorizationUsecase_Expecter {
	return &AuthorizationUsecase_Expecter{mock: &_m.Mock}
}

// BatchCheck provides a mock function with given fields: ctx, accountID, checks, minVersion
func (_m *AuthorizationUsecase) BatchCheck(ctx context.Context, accountID string, checks []domain.PermissionCheck, minVersion int64) ([]domain.PermissionDecision, error) {
	ret := _m.Called(ctx, accountID, checks, minVersion)

	if len(ret) == 0 {
		panic("no return value specified for BatchCheck")
	}

	var r0 []domain.PermissionDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.PermissionCheck, int64) ([]domain.PermissionDecision, error)); ok {
		return rf(ctx, accountID, checks, minVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.PermissionCheck, int64) []domain.PermissionDecision); ok {
		r0 = rf(ctx, accountID, checks, minVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PermissionDecision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []domain.PermissionCheck, int64) error); ok {
		r1 = rf(ctx, accountID, checks, minVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizationUsecase_BatchCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCheck'
type AuthorizationUsecase_BatchCheck_Call struct {
	*mock.Call
}

// BatchCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - checks []domain.PermissionCheck
//   - minVersion int64
func (_e *AuthorizationUsecase_Expecter) BatchCheck(ctx interface{}, accountID interface{}, checks interface{}, minVersion interface{}) *AuthorizationUsecase_BatchCheck_Call {
	return &AuthorizationUsecase_BatchCheck_Call{Call: _e.mock.On("BatchCheck", ctx, accountID, checks, minVersion)}
}

func (_c *AuthorizationUsecase_BatchCheck_Call) Run(run func(ctx context.Context, accountID string, checks []domain.PermissionCheck, minVersion int64)) *AuthorizationUsecase_BatchCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.PermissionCheck), args[3].(int64))
	})
	return _c
}

func (_c *AuthorizationUsecase_BatchCheck_Call) Return(_a0 []domain.PermissionDecision, _a1 error) *AuthorizationUsecase_BatchCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizationUsecase_BatchCheck_Call) RunAndReturn(run func(context.Context, string, []domain.PermissionCheck, int64) ([]domain.PermissionDecision, error)) *AuthorizationUsecase_BatchCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function with given fields: ctx, accountID, resourceID, permissionID, minVersion
func (_m *AuthorizationUsecase) Check(ctx context.Context, accountID string, resourceID string, permissionID string, minVersion int64) (bool, error) {
	ret := _m.Called(ctx, accountID, resourceID, permissionID, minVersion)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (bool, error)); ok {
		return rf(ctx, accountID, resourceID, permissionID, minVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) bool); ok {
		r0 = rf(ctx, accountID, resourceID, permissionID, minVersion)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, accountID, resourceID, permissionID, minVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizationUsecase_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type AuthorizationUsecase_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - resourceID string
//   - permissionID string
//   - minVersion int64
func (_e *AuthorizationUsecase_Expecter) Check(ctx interface{}, accountID interface{}, resourceID interface{}, permissionID interface{}, minVersion interface{}) *AuthorizationUsecase_Check_Call {
	return &AuthorizationUsecase_Check_Call{Call: _e.mock.On("Check", ctx, accountID, resourceID, permissionID, minVersion)}
}

func (_c *AuthorizationUsecase_Check_Call) Run(run func(ctx context.Context, accountID string, resourceID string, permissionID string, minVersion int64)) *AuthorizationUsecase_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *AuthorizationUsecase_Check_Call) Return(_a0 bool, _a1 error) *AuthorizationUsecase_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizationUsecase_Check_Call) RunAndReturn(run func(context.Context, string, string, string, int64) (bool, error)) *AuthorizationUsecase_Check_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessible provides a mock function with given fields: ctx, accountID, permissionID, minVersion
func (_m *AuthorizationUsecase) ListAccessible(ctx context.Context, accountID string, permissionID string, minVersion int64) ([]string, error) {
	ret := _m.Called(ctx, accountID, permissionID, minVersion)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessible")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) ([]string, error)); ok {
		return rf(ctx, accountID, permissionID, minVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) []string); ok {
		r0 = rf(ctx, accountID, permissionID, minVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, accountID, permissionID, minVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizationUsecase_ListAccessible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessible'
type AuthorizationUsecase_ListAccessible_Call struct {
	*mock.Call
}

// ListAccessible is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - permissionID string
//   - minVersion int64
func (_e *AuthorizationUsecase_Expecter) ListAccessible(ctx interface{}, accountID interface{}, permissionID interface{}, minVersion interface{}) *AuthorizationUsecase_ListAccessible_Call {
	return &AuthorizationUsecase_ListAccessible_Call{Call: _e.mock.On("ListAccessible", ctx, accountID, permissionID, minVersion)}
}

func (_c *AuthorizationUsecase_ListAccessible_Call) Run(run func(ctx context.Context, accountID string, permissionID string, minVersion int64)) *AuthorizationUsecase_ListAccessible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *AuthorizationUsecase_ListAccessible_Call) Return(_a0 []string, _a1 error) *AuthorizationUsecase_ListAccessible_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizationUsecase_ListAccessible_Call) RunAndReturn(run func(context.Context, string, string, int64) ([]string, error)) *AuthorizationUsecase_ListAccessible_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx
func (_m *AuthorizationUsecase) Refresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthorizationUsecase_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthorizationUsecase_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthorizationUsecase_Expecter) Refresh(ctx interface{}) *AuthorizationUsecase_Refresh_Call {
	return &AuthorizationUsecase_Refresh_Call{Call: _e.mock.On("Refresh", ctx)}
}

func (_c *AuthorizationUsecase_Refresh_Call) Run(run func(ctx context.Context)) *AuthorizationUsecase_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthorizationUsecase_Refresh_Call) Return(_a0 error) *AuthorizationUsecase_Refresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthorizationUsecase_Refresh_Call) RunAndReturn(run func(context.Context) error) *AuthorizationUsecase_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields: ctx
func (_m *AuthorizationUsecase) Version(ctx context.Context) (int64, int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthorizationUsecase_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type AuthorizationUsecase_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthorizationUsecase_Expecter) Version(ctx interface{}) *AuthorizationUsecase_Version_Call {
	return &AuthorizationUsecase_Version_Call{Call: _e.mock.On("Version", ctx)}
}

func (_c *AuthorizationUsecase_Version_Call) Run(run func(ctx context.Context)) *AuthorizationUsecase_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthorizationUsecase_Version_Call) Return(write int64, projection int64, err error) *AuthorizationUsecase_Version_Call {
	_c.Call.Return(write, projection, err)
	return _c
}

func (_c *AuthorizationUsecase_Version_Call) RunAndReturn(run func(context.Context) (int64, int64, error)) *AuthorizationUsecase_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizationUsecase creates a new instance of AuthorizationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationUsecase {
	mock := &AuthorizationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
