// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthorizationProjectionRepository is an autogenerated mock type for the AuthorizationProjectionRepository type
type AuthorizationProjectionRepository struct {
	mock.Mock
}

type AuthorizationProjectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationProjectionRepository) EXPECT() *AuthorizationProjectionRepository_Expecter {
	return &AuthorizationProjectionRepository_Expecter{mock: &_m.Mock}
}

// Refresh provides a mock function with given fields: ctx
func (_m *AuthorizationProjectionRepository) Refresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthorizationProjectionRepository_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthorizationProjectionRepository_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthorizationProjectionRepository_Expecter) Refresh(ctx interface{}) *AuthorizationProjectionRepository_Refresh_Call {
	return &AuthorizationProjectionRepository_Refresh_Call{Call: _e.mock.On("Refresh", ctx)}
}

func (_c *AuthorizationProjectionRepository_Refresh_Call) Run(run func(ctx context.Context)) *AuthorizationProjectionRepository_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuthorizationProjectionRepository_Refresh_Call) Return(_a0 error) *AuthorizationProjectionRepository_Refresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthorizationProjectionRepository_Refresh_Call) RunAndReturn(run func(context.Context) error) *AuthorizationProjectionRepository_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizationProjectionRepository creates a new instance of AuthorizationProjectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationProjectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationProjectionRepository {
	mock := &AuthorizationProjectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
