// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// BindingUsecase is an autogenerated mock type for the BindingUsecase type
type BindingUsecase struct {
	mock.Mock
}

type BindingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *BindingUsecase) EXPECT() *BindingUsecase_Expecter {
	return &BindingUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, b
func (_m *BindingUsecase) Create(ctx context.Context, b domain.Binding) (domain.Binding, error) {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Binding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Binding) (domain.Binding, error)); ok {
		return rf(ctx, b)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Binding) domain.Binding); ok {
		r0 = rf(ctx, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Binding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Binding) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BindingUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b domain.Binding
func (_e *BindingUsecase_Expecter) Create(ctx interface{}, b interface{}) *BindingUsecase_Create_Call {
	return &BindingUsecase_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *BindingUsecase_Create_Call) Run(run func(ctx context.Context, b domain.Binding)) *BindingUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Binding))
	})
	return _c
}

func (_c *BindingUsecase_Create_Call) Return(_a0 domain.Binding, _a1 error) *BindingUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Binding) (domain.Binding, error)) *BindingUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *BindingUsecase) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindingUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BindingUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *BindingUsecase_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *BindingUsecase_Delete_Call {
	return &BindingUsecase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *BindingUsecase_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *BindingUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *BindingUsecase_Delete_Call) Return(_a0 error) *BindingUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingUsecase_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *BindingUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *BindingUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Binding, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Binding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Binding, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Binding); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Binding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BindingUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *BindingUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *BindingUsecase_Get_Call {
	return &BindingUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *BindingUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *BindingUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *BindingUsecase_Get_Call) Return(_a0 domain.Binding, _a1 error) *BindingUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Binding, error)) *BindingUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *BindingUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Binding], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Binding]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Binding], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Binding]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Binding])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type BindingUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *BindingUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *BindingUsecase_List_Call {
	return &BindingUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *BindingUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *BindingUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *BindingUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Binding], _a1 error) *BindingUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Binding], error)) *BindingUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewBindingUsecase creates a new instance of BindingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBindingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BindingUsecase {
	mock := &BindingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
