// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"

	time "time"
)

// BindingRepository is an autogenerated mock type for the BindingRepository type
type BindingRepository struct {
	mock.Mock
}

type BindingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BindingRepository) EXPECT() *BindingRepository_Expecter {
	return &BindingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *BindingRepository) Create(_a0 context.Context, _a1 domain.Binding) (domain.Binding, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Binding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Binding) (domain.Binding, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Binding) domain.Binding); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Binding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Binding) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BindingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Binding
func (_e *BindingRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *BindingRepository_Create_Call {
	return &BindingRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *BindingRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.Binding)) *BindingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Binding))
	})
	return _c
}

func (_c *BindingRepository_Create_Call) Return(_a0 domain.Binding, _a1 error) *BindingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Binding) (domain.Binding, error)) *BindingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *BindingRepository) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindingRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BindingRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *BindingRepository_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *BindingRepository_Delete_Call {
	return &BindingRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *BindingRepository_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *BindingRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *BindingRepository_Delete_Call) Return(_a0 error) *BindingRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BindingRepository_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *BindingRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx, now
func (_m *BindingRepository) DeleteExpired(ctx context.Context, now time.Time) (int64, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type BindingRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *BindingRepository_Expecter) DeleteExpired(ctx interface{}, now interface{}) *BindingRepository_DeleteExpired_Call {
	return &BindingRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx, now)}
}

func (_c *BindingRepository_DeleteExpired_Call) Run(run func(ctx context.Context, now time.Time)) *BindingRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *BindingRepository_DeleteExpired_Call) Return(_a0 int64, _a1 error) *BindingRepository_DeleteExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *BindingRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *BindingRepository) Get(ctx context.Context, opts ...search.Option) (domain.Binding, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Binding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Binding, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Binding); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Binding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BindingRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *BindingRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *BindingRepository_Get_Call {
	return &BindingRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *BindingRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *BindingRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *BindingRepository_Get_Call) Return(_a0 domain.Binding, _a1 error) *BindingRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Binding, error)) *BindingRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *BindingRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Binding], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Binding]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Binding], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Binding]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Binding])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type BindingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *BindingRepository_Expecter) List(ctx interface{}, opts ...interface{}) *BindingRepository_List_Call {
	return &BindingRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *BindingRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *BindingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *BindingRepository_List_Call) Return(_a0 resource.ListResponse[domain.Binding], _a1 error) *BindingRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BindingRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Binding], error)) *BindingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewBindingRepository creates a new instance of BindingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBindingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BindingRepository {
	mock := &BindingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
