// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	domain "github.com/fromforgesoftware/aegis/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

type Connector_Expecter struct {
	mock *mock.Mock
}

func (_m *Connector) EXPECT() *Connector_Expecter {
	return &Connector_Expecter{mock: &_m.Mock}
}

// Kind provides a mock function with no fields
func (_m *Connector) Kind() domain.ExternalIDPKind {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 domain.ExternalIDPKind
	if rf, ok := ret.Get(0).(func() domain.ExternalIDPKind); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.ExternalIDPKind)
	}

	return r0
}

// Connector_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type Connector_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *Connector_Expecter) Kind() *Connector_Kind_Call {
	return &Connector_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *Connector_Kind_Call) Run(run func()) *Connector_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_Kind_Call) Return(_a0 domain.ExternalIDPKind) *Connector_Kind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_Kind_Call) RunAndReturn(run func() domain.ExternalIDPKind) *Connector_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, cfg, rawToken
func (_m *Connector) Verify(ctx context.Context, cfg domain.ExternalIDPConfig, rawToken string) (app.ExternalUser, error) {
	ret := _m.Called(ctx, cfg, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 app.ExternalUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExternalIDPConfig, string) (app.ExternalUser, error)); ok {
		return rf(ctx, cfg, rawToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExternalIDPConfig, string) app.ExternalUser); ok {
		r0 = rf(ctx, cfg, rawToken)
	} else {
		r0 = ret.Get(0).(app.ExternalUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ExternalIDPConfig, string) error); ok {
		r1 = rf(ctx, cfg, rawToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Connector_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg domain.ExternalIDPConfig
//   - rawToken string
func (_e *Connector_Expecter) Verify(ctx interface{}, cfg interface{}, rawToken interface{}) *Connector_Verify_Call {
	return &Connector_Verify_Call{Call: _e.mock.On("Verify", ctx, cfg, rawToken)}
}

func (_c *Connector_Verify_Call) Run(run func(ctx context.Context, cfg domain.ExternalIDPConfig, rawToken string)) *Connector_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ExternalIDPConfig), args[2].(string))
	})
	return _c
}

func (_c *Connector_Verify_Call) Return(_a0 app.ExternalUser, _a1 error) *Connector_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Connector_Verify_Call) RunAndReturn(run func(context.Context, domain.ExternalIDPConfig, string) (app.ExternalUser, error)) *Connector_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
