// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	password "github.com/fromforgesoftware/go-kit/auth/password"
	mock "github.com/stretchr/testify/mock"
)

// CredentialRepository is an autogenerated mock type for the CredentialRepository type
type CredentialRepository struct {
	mock.Mock
}

type CredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialRepository) EXPECT() *CredentialRepository_Expecter {
	return &CredentialRepository_Expecter{mock: &_m.Mock}
}

// GetPasswordHash provides a mock function with given fields: ctx, accountID
func (_m *CredentialRepository) GetPasswordHash(ctx context.Context, accountID string) (string, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialRepository_GetPasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordHash'
type CredentialRepository_GetPasswordHash_Call struct {
	*mock.Call
}

// GetPasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *CredentialRepository_Expecter) GetPasswordHash(ctx interface{}, accountID interface{}) *CredentialRepository_GetPasswordHash_Call {
	return &CredentialRepository_GetPasswordHash_Call{Call: _e.mock.On("GetPasswordHash", ctx, accountID)}
}

func (_c *CredentialRepository_GetPasswordHash_Call) Run(run func(ctx context.Context, accountID string)) *CredentialRepository_GetPasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CredentialRepository_GetPasswordHash_Call) Return(_a0 string, _a1 error) *CredentialRepository_GetPasswordHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialRepository_GetPasswordHash_Call) RunAndReturn(run func(context.Context, string) (string, error)) *CredentialRepository_GetPasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function with given fields: ctx, accountID, cred
func (_m *CredentialRepository) SetPassword(ctx context.Context, accountID string, cred password.Hashed) error {
	ret := _m.Called(ctx, accountID, cred)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, password.Hashed) error); ok {
		r0 = rf(ctx, accountID, cred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialRepository_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type CredentialRepository_SetPassword_Call struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - cred password.Hashed
func (_e *CredentialRepository_Expecter) SetPassword(ctx interface{}, accountID interface{}, cred interface{}) *CredentialRepository_SetPassword_Call {
	return &CredentialRepository_SetPassword_Call{Call: _e.mock.On("SetPassword", ctx, accountID, cred)}
}

func (_c *CredentialRepository_SetPassword_Call) Run(run func(ctx context.Context, accountID string, cred password.Hashed)) *CredentialRepository_SetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(password.Hashed))
	})
	return _c
}

func (_c *CredentialRepository_SetPassword_Call) Return(_a0 error) *CredentialRepository_SetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CredentialRepository_SetPassword_Call) RunAndReturn(run func(context.Context, string, password.Hashed) error) *CredentialRepository_SetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredentialRepository creates a new instance of CredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialRepository {
	mock := &CredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
