// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	search "github.com/fromforgesoftware/go-kit/search"
)

// FlowRepository is an autogenerated mock type for the FlowRepository type
type FlowRepository struct {
	mock.Mock
}

type FlowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowRepository) EXPECT() *FlowRepository_Expecter {
	return &FlowRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *FlowRepository) Create(_a0 context.Context, _a1 domain.Flow) (domain.Flow, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Flow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Flow) (domain.Flow, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Flow) domain.Flow); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Flow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Flow) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlowRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FlowRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Flow
func (_e *FlowRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *FlowRepository_Create_Call {
	return &FlowRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *FlowRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.Flow)) *FlowRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Flow))
	})
	return _c
}

func (_c *FlowRepository_Create_Call) Return(_a0 domain.Flow, _a1 error) *FlowRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlowRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Flow) (domain.Flow, error)) *FlowRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *FlowRepository) Get(ctx context.Context, opts ...search.Option) (domain.Flow, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Flow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Flow, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Flow); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Flow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlowRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type FlowRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *FlowRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *FlowRepository_Get_Call {
	return &FlowRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *FlowRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *FlowRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *FlowRepository_Get_Call) Return(_a0 domain.Flow, _a1 error) *FlowRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlowRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Flow, error)) *FlowRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: _a0, _a1
func (_m *FlowRepository) Patch(_a0 context.Context, _a1 ...repository.PatchOption) ([]domain.Flow, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 []domain.Flow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) ([]domain.Flow, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) []domain.Flow); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Flow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...repository.PatchOption) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlowRepository_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type FlowRepository_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...repository.PatchOption
func (_e *FlowRepository_Expecter) Patch(_a0 interface{}, _a1 ...interface{}) *FlowRepository_Patch_Call {
	return &FlowRepository_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *FlowRepository_Patch_Call) Run(run func(_a0 context.Context, _a1 ...repository.PatchOption)) *FlowRepository_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repository.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(repository.PatchOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *FlowRepository_Patch_Call) Return(_a0 []domain.Flow, _a1 error) *FlowRepository_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlowRepository_Patch_Call) RunAndReturn(run func(context.Context, ...repository.PatchOption) ([]domain.Flow, error)) *FlowRepository_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// NewFlowRepository creates a new instance of FlowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowRepository {
	mock := &FlowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
