// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GroupMemberRepository is an autogenerated mock type for the GroupMemberRepository type
type GroupMemberRepository struct {
	mock.Mock
}

type GroupMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GroupMemberRepository) EXPECT() *GroupMemberRepository_Expecter {
	return &GroupMemberRepository_Expecter{mock: &_m.Mock}
}

// CreateMany provides a mock function with given fields: ctx, groupID, accountIDs
func (_m *GroupMemberRepository) CreateMany(ctx context.Context, groupID string, accountIDs []string) error {
	ret := _m.Called(ctx, groupID, accountIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, groupID, accountIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type GroupMemberRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - accountIDs []string
func (_e *GroupMemberRepository_Expecter) CreateMany(ctx interface{}, groupID interface{}, accountIDs interface{}) *GroupMemberRepository_CreateMany_Call {
	return &GroupMemberRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, groupID, accountIDs)}
}

func (_c *GroupMemberRepository_CreateMany_Call) Run(run func(ctx context.Context, groupID string, accountIDs []string)) *GroupMemberRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *GroupMemberRepository_CreateMany_Call) Return(_a0 error) *GroupMemberRepository_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GroupMemberRepository_CreateMany_Call) RunAndReturn(run func(context.Context, string, []string) error) *GroupMemberRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByGroup provides a mock function with given fields: ctx, groupID
func (_m *GroupMemberRepository) DeleteByGroup(ctx context.Context, groupID string) error {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberRepository_DeleteByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByGroup'
type GroupMemberRepository_DeleteByGroup_Call struct {
	*mock.Call
}

// DeleteByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *GroupMemberRepository_Expecter) DeleteByGroup(ctx interface{}, groupID interface{}) *GroupMemberRepository_DeleteByGroup_Call {
	return &GroupMemberRepository_DeleteByGroup_Call{Call: _e.mock.On("DeleteByGroup", ctx, groupID)}
}

func (_c *GroupMemberRepository_DeleteByGroup_Call) Run(run func(ctx context.Context, groupID string)) *GroupMemberRepository_DeleteByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GroupMemberRepository_DeleteByGroup_Call) Return(_a0 error) *GroupMemberRepository_DeleteByGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GroupMemberRepository_DeleteByGroup_Call) RunAndReturn(run func(context.Context, string) error) *GroupMemberRepository_DeleteByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccountIDs provides a mock function with given fields: ctx, groupID
func (_m *GroupMemberRepository) ListAccountIDs(ctx context.Context, groupID string) ([]string, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GroupMemberRepository_ListAccountIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccountIDs'
type GroupMemberRepository_ListAccountIDs_Call struct {
	*mock.Call
}

// ListAccountIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *GroupMemberRepository_Expecter) ListAccountIDs(ctx interface{}, groupID interface{}) *GroupMemberRepository_ListAccountIDs_Call {
	return &GroupMemberRepository_ListAccountIDs_Call{Call: _e.mock.On("ListAccountIDs", ctx, groupID)}
}

func (_c *GroupMemberRepository_ListAccountIDs_Call) Run(run func(ctx context.Context, groupID string)) *GroupMemberRepository_ListAccountIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GroupMemberRepository_ListAccountIDs_Call) Return(_a0 []string, _a1 error) *GroupMemberRepository_ListAccountIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GroupMemberRepository_ListAccountIDs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *GroupMemberRepository_ListAccountIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewGroupMemberRepository creates a new instance of GroupMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupMemberRepository {
	mock := &GroupMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
