// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	mock "github.com/stretchr/testify/mock"
)

// IdentityBrokerUsecase is an autogenerated mock type for the IdentityBrokerUsecase type
type IdentityBrokerUsecase struct {
	mock.Mock
}

type IdentityBrokerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityBrokerUsecase) EXPECT() *IdentityBrokerUsecase_Expecter {
	return &IdentityBrokerUsecase_Expecter{mock: &_m.Mock}
}

// ResolveAccount provides a mock function with given fields: ctx, in
func (_m *IdentityBrokerUsecase) ResolveAccount(ctx context.Context, in app.ResolveAccountInput) (app.ResolveAccountResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAccount")
	}

	var r0 app.ResolveAccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, app.ResolveAccountInput) (app.ResolveAccountResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, app.ResolveAccountInput) app.ResolveAccountResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(app.ResolveAccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, app.ResolveAccountInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityBrokerUsecase_ResolveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAccount'
type IdentityBrokerUsecase_ResolveAccount_Call struct {
	*mock.Call
}

// ResolveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - in app.ResolveAccountInput
func (_e *IdentityBrokerUsecase_Expecter) ResolveAccount(ctx interface{}, in interface{}) *IdentityBrokerUsecase_ResolveAccount_Call {
	return &IdentityBrokerUsecase_ResolveAccount_Call{Call: _e.mock.On("ResolveAccount", ctx, in)}
}

func (_c *IdentityBrokerUsecase_ResolveAccount_Call) Run(run func(ctx context.Context, in app.ResolveAccountInput)) *IdentityBrokerUsecase_ResolveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.ResolveAccountInput))
	})
	return _c
}

func (_c *IdentityBrokerUsecase_ResolveAccount_Call) Return(_a0 app.ResolveAccountResult, _a1 error) *IdentityBrokerUsecase_ResolveAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityBrokerUsecase_ResolveAccount_Call) RunAndReturn(run func(context.Context, app.ResolveAccountInput) (app.ResolveAccountResult, error)) *IdentityBrokerUsecase_ResolveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentityBrokerUsecase creates a new instance of IdentityBrokerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityBrokerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityBrokerUsecase {
	mock := &IdentityBrokerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
