// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// InvitationUsecase is an autogenerated mock type for the InvitationUsecase type
type InvitationUsecase struct {
	mock.Mock
}

type InvitationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationUsecase) EXPECT() *InvitationUsecase_Expecter {
	return &InvitationUsecase_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function with given fields: ctx, token, accountID
func (_m *InvitationUsecase) Accept(ctx context.Context, token string, accountID string) error {
	ret := _m.Called(ctx, token, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationUsecase_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type InvitationUsecase_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - accountID string
func (_e *InvitationUsecase_Expecter) Accept(ctx interface{}, token interface{}, accountID interface{}) *InvitationUsecase_Accept_Call {
	return &InvitationUsecase_Accept_Call{Call: _e.mock.On("Accept", ctx, token, accountID)}
}

func (_c *InvitationUsecase_Accept_Call) Run(run func(ctx context.Context, token string, accountID string)) *InvitationUsecase_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InvitationUsecase_Accept_Call) Return(_a0 error) *InvitationUsecase_Accept_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationUsecase_Accept_Call) RunAndReturn(run func(context.Context, string, string) error) *InvitationUsecase_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, inv
func (_m *InvitationUsecase) Create(ctx context.Context, inv domain.Invitation) (domain.Invitation, error) {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) (domain.Invitation, error)); ok {
		return rf(ctx, inv)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) domain.Invitation); ok {
		r0 = rf(ctx, inv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Invitation) error); ok {
		r1 = rf(ctx, inv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvitationUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - inv domain.Invitation
func (_e *InvitationUsecase_Expecter) Create(ctx interface{}, inv interface{}) *InvitationUsecase_Create_Call {
	return &InvitationUsecase_Create_Call{Call: _e.mock.On("Create", ctx, inv)}
}

func (_c *InvitationUsecase_Create_Call) Run(run func(ctx context.Context, inv domain.Invitation)) *InvitationUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Invitation))
	})
	return _c
}

func (_c *InvitationUsecase_Create_Call) Return(_a0 domain.Invitation, _a1 error) *InvitationUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Invitation) (domain.Invitation, error)) *InvitationUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *InvitationUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Invitation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Invitation, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Invitation); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InvitationUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *InvitationUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *InvitationUsecase_Get_Call {
	return &InvitationUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *InvitationUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *InvitationUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *InvitationUsecase_Get_Call) Return(_a0 domain.Invitation, _a1 error) *InvitationUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Invitation, error)) *InvitationUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *InvitationUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Invitation], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Invitation]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Invitation], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Invitation]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Invitation])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InvitationUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *InvitationUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *InvitationUsecase_List_Call {
	return &InvitationUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *InvitationUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *InvitationUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *InvitationUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Invitation], _a1 error) *InvitationUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Invitation], error)) *InvitationUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationUsecase creates a new instance of InvitationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationUsecase {
	mock := &InvitationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
