// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"

	time "time"
)

// InvitationRepository is an autogenerated mock type for the InvitationRepository type
type InvitationRepository struct {
	mock.Mock
}

type InvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationRepository) EXPECT() *InvitationRepository_Expecter {
	return &InvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *InvitationRepository) Create(_a0 context.Context, _a1 domain.Invitation) (domain.Invitation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) (domain.Invitation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) domain.Invitation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Invitation) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Invitation
func (_e *InvitationRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *InvitationRepository_Create_Call {
	return &InvitationRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *InvitationRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.Invitation)) *InvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Invitation))
	})
	return _c
}

func (_c *InvitationRepository_Create_Call) Return(_a0 domain.Invitation, _a1 error) *InvitationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Invitation) (domain.Invitation, error)) *InvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *InvitationRepository) Get(ctx context.Context, opts ...search.Option) (domain.Invitation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Invitation, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Invitation); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InvitationRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *InvitationRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *InvitationRepository_Get_Call {
	return &InvitationRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *InvitationRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *InvitationRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *InvitationRepository_Get_Call) Return(_a0 domain.Invitation, _a1 error) *InvitationRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Invitation, error)) *InvitationRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *InvitationRepository) GetByTokenHash(ctx context.Context, tokenHash string) (domain.Invitation, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Invitation, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Invitation); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type InvitationRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *InvitationRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *InvitationRepository_GetByTokenHash_Call {
	return &InvitationRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *InvitationRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *InvitationRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InvitationRepository_GetByTokenHash_Call) Return(_a0 domain.Invitation, _a1 error) *InvitationRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (domain.Invitation, error)) *InvitationRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *InvitationRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Invitation], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Invitation]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Invitation], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Invitation]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Invitation])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InvitationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *InvitationRepository_Expecter) List(ctx interface{}, opts ...interface{}) *InvitationRepository_List_Call {
	return &InvitationRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *InvitationRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *InvitationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *InvitationRepository_List_Call) Return(_a0 resource.ListResponse[domain.Invitation], _a1 error) *InvitationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Invitation], error)) *InvitationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAccepted provides a mock function with given fields: ctx, id, at
func (_m *InvitationRepository) MarkAccepted(ctx context.Context, id string, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkAccepted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_MarkAccepted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAccepted'
type InvitationRepository_MarkAccepted_Call struct {
	*mock.Call
}

// MarkAccepted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - at time.Time
func (_e *InvitationRepository_Expecter) MarkAccepted(ctx interface{}, id interface{}, at interface{}) *InvitationRepository_MarkAccepted_Call {
	return &InvitationRepository_MarkAccepted_Call{Call: _e.mock.On("MarkAccepted", ctx, id, at)}
}

func (_c *InvitationRepository_MarkAccepted_Call) Run(run func(ctx context.Context, id string, at time.Time)) *InvitationRepository_MarkAccepted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *InvitationRepository_MarkAccepted_Call) Return(_a0 error) *InvitationRepository_MarkAccepted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_MarkAccepted_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *InvitationRepository_MarkAccepted_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationRepository creates a new instance of InvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationRepository {
	mock := &InvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
