// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MFAUsecase is an autogenerated mock type for the MFAUsecase type
type MFAUsecase struct {
	mock.Mock
}

type MFAUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MFAUsecase) EXPECT() *MFAUsecase_Expecter {
	return &MFAUsecase_Expecter{mock: &_m.Mock}
}

// ConfirmTOTP provides a mock function with given fields: ctx, accountID, code
func (_m *MFAUsecase) ConfirmTOTP(ctx context.Context, accountID string, code string) ([]string, error) {
	ret := _m.Called(ctx, accountID, code)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmTOTP")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, accountID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, accountID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MFAUsecase_ConfirmTOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmTOTP'
type MFAUsecase_ConfirmTOTP_Call struct {
	*mock.Call
}

// ConfirmTOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - code string
func (_e *MFAUsecase_Expecter) ConfirmTOTP(ctx interface{}, accountID interface{}, code interface{}) *MFAUsecase_ConfirmTOTP_Call {
	return &MFAUsecase_ConfirmTOTP_Call{Call: _e.mock.On("ConfirmTOTP", ctx, accountID, code)}
}

func (_c *MFAUsecase_ConfirmTOTP_Call) Run(run func(ctx context.Context, accountID string, code string)) *MFAUsecase_ConfirmTOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MFAUsecase_ConfirmTOTP_Call) Return(recoveryCodes []string, err error) *MFAUsecase_ConfirmTOTP_Call {
	_c.Call.Return(recoveryCodes, err)
	return _c
}

func (_c *MFAUsecase_ConfirmTOTP_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MFAUsecase_ConfirmTOTP_Call {
	_c.Call.Return(run)
	return _c
}

// EnrollTOTP provides a mock function with given fields: ctx, accountID, issuer, accountLabel
func (_m *MFAUsecase) EnrollTOTP(ctx context.Context, accountID string, issuer string, accountLabel string) (string, string, error) {
	ret := _m.Called(ctx, accountID, issuer, accountLabel)

	if len(ret) == 0 {
		panic("no return value specified for EnrollTOTP")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, string, error)); ok {
		return rf(ctx, accountID, issuer, accountLabel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, accountID, issuer, accountLabel)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, accountID, issuer, accountLabel)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, accountID, issuer, accountLabel)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MFAUsecase_EnrollTOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrollTOTP'
type MFAUsecase_EnrollTOTP_Call struct {
	*mock.Call
}

// EnrollTOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - issuer string
//   - accountLabel string
func (_e *MFAUsecase_Expecter) EnrollTOTP(ctx interface{}, accountID interface{}, issuer interface{}, accountLabel interface{}) *MFAUsecase_EnrollTOTP_Call {
	return &MFAUsecase_EnrollTOTP_Call{Call: _e.mock.On("EnrollTOTP", ctx, accountID, issuer, accountLabel)}
}

func (_c *MFAUsecase_EnrollTOTP_Call) Run(run func(ctx context.Context, accountID string, issuer string, accountLabel string)) *MFAUsecase_EnrollTOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MFAUsecase_EnrollTOTP_Call) Return(secret string, provisioningURI string, err error) *MFAUsecase_EnrollTOTP_Call {
	_c.Call.Return(secret, provisioningURI, err)
	return _c
}

func (_c *MFAUsecase_EnrollTOTP_Call) RunAndReturn(run func(context.Context, string, string, string) (string, string, error)) *MFAUsecase_EnrollTOTP_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateRecoveryCodes provides a mock function with given fields: ctx, accountID
func (_m *MFAUsecase) RegenerateRecoveryCodes(ctx context.Context, accountID string) ([]string, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateRecoveryCodes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MFAUsecase_RegenerateRecoveryCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateRecoveryCodes'
type MFAUsecase_RegenerateRecoveryCodes_Call struct {
	*mock.Call
}

// RegenerateRecoveryCodes is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MFAUsecase_Expecter) RegenerateRecoveryCodes(ctx interface{}, accountID interface{}) *MFAUsecase_RegenerateRecoveryCodes_Call {
	return &MFAUsecase_RegenerateRecoveryCodes_Call{Call: _e.mock.On("RegenerateRecoveryCodes", ctx, accountID)}
}

func (_c *MFAUsecase_RegenerateRecoveryCodes_Call) Run(run func(ctx context.Context, accountID string)) *MFAUsecase_RegenerateRecoveryCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MFAUsecase_RegenerateRecoveryCodes_Call) Return(_a0 []string, _a1 error) *MFAUsecase_RegenerateRecoveryCodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MFAUsecase_RegenerateRecoveryCodes_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MFAUsecase_RegenerateRecoveryCodes_Call {
	_c.Call.Return(run)
	return _c
}

// StepUp provides a mock function with given fields: ctx, accountID, factor, proof
func (_m *MFAUsecase) StepUp(ctx context.Context, accountID string, factor domain.MFAFactor, proof string) (string, string, time.Time, error) {
	ret := _m.Called(ctx, accountID, factor, proof)

	if len(ret) == 0 {
		panic("no return value specified for StepUp")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MFAFactor, string) (string, string, time.Time, error)); ok {
		return rf(ctx, accountID, factor, proof)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MFAFactor, string) string); ok {
		r0 = rf(ctx, accountID, factor, proof)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.MFAFactor, string) string); ok {
		r1 = rf(ctx, accountID, factor, proof)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, domain.MFAFactor, string) time.Time); ok {
		r2 = rf(ctx, accountID, factor, proof)
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, domain.MFAFactor, string) error); ok {
		r3 = rf(ctx, accountID, factor, proof)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MFAUsecase_StepUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StepUp'
type MFAUsecase_StepUp_Call struct {
	*mock.Call
}

// StepUp is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - factor domain.MFAFactor
//   - proof string
func (_e *MFAUsecase_Expecter) StepUp(ctx interface{}, accountID interface{}, factor interface{}, proof interface{}) *MFAUsecase_StepUp_Call {
	return &MFAUsecase_StepUp_Call{Call: _e.mock.On("StepUp", ctx, accountID, factor, proof)}
}

func (_c *MFAUsecase_StepUp_Call) Run(run func(ctx context.Context, accountID string, factor domain.MFAFactor, proof string)) *MFAUsecase_StepUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.MFAFactor), args[3].(string))
	})
	return _c
}

func (_c *MFAUsecase_StepUp_Call) Return(token string, acr string, expiresAt time.Time, err error) *MFAUsecase_StepUp_Call {
	_c.Call.Return(token, acr, expiresAt, err)
	return _c
}

func (_c *MFAUsecase_StepUp_Call) RunAndReturn(run func(context.Context, string, domain.MFAFactor, string) (string, string, time.Time, error)) *MFAUsecase_StepUp_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRecoveryCode provides a mock function with given fields: ctx, accountID, code
func (_m *MFAUsecase) VerifyRecoveryCode(ctx context.Context, accountID string, code string) (bool, error) {
	ret := _m.Called(ctx, accountID, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRecoveryCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, accountID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, accountID, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MFAUsecase_VerifyRecoveryCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRecoveryCode'
type MFAUsecase_VerifyRecoveryCode_Call struct {
	*mock.Call
}

// VerifyRecoveryCode is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - code string
func (_e *MFAUsecase_Expecter) VerifyRecoveryCode(ctx interface{}, accountID interface{}, code interface{}) *MFAUsecase_VerifyRecoveryCode_Call {
	return &MFAUsecase_VerifyRecoveryCode_Call{Call: _e.mock.On("VerifyRecoveryCode", ctx, accountID, code)}
}

func (_c *MFAUsecase_VerifyRecoveryCode_Call) Run(run func(ctx context.Context, accountID string, code string)) *MFAUsecase_VerifyRecoveryCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MFAUsecase_VerifyRecoveryCode_Call) Return(_a0 bool, _a1 error) *MFAUsecase_VerifyRecoveryCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MFAUsecase_VerifyRecoveryCode_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MFAUsecase_VerifyRecoveryCode_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyStepUp provides a mock function with given fields: ctx, token
func (_m *MFAUsecase) VerifyStepUp(ctx context.Context, token string) (domain.StepUpToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyStepUp")
	}

	var r0 domain.StepUpToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StepUpToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StepUpToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.StepUpToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MFAUsecase_VerifyStepUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyStepUp'
type MFAUsecase_VerifyStepUp_Call struct {
	*mock.Call
}

// VerifyStepUp is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MFAUsecase_Expecter) VerifyStepUp(ctx interface{}, token interface{}) *MFAUsecase_VerifyStepUp_Call {
	return &MFAUsecase_VerifyStepUp_Call{Call: _e.mock.On("VerifyStepUp", ctx, token)}
}

func (_c *MFAUsecase_VerifyStepUp_Call) Run(run func(ctx context.Context, token string)) *MFAUsecase_VerifyStepUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MFAUsecase_VerifyStepUp_Call) Return(_a0 domain.StepUpToken, _a1 error) *MFAUsecase_VerifyStepUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MFAUsecase_VerifyStepUp_Call) RunAndReturn(run func(context.Context, string) (domain.StepUpToken, error)) *MFAUsecase_VerifyStepUp_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyTOTP provides a mock function with given fields: ctx, accountID, code
func (_m *MFAUsecase) VerifyTOTP(ctx context.Context, accountID string, code string) (bool, error) {
	ret := _m.Called(ctx, accountID, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyTOTP")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, accountID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, accountID, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MFAUsecase_VerifyTOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyTOTP'
type MFAUsecase_VerifyTOTP_Call struct {
	*mock.Call
}

// VerifyTOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - code string
func (_e *MFAUsecase_Expecter) VerifyTOTP(ctx interface{}, accountID interface{}, code interface{}) *MFAUsecase_VerifyTOTP_Call {
	return &MFAUsecase_VerifyTOTP_Call{Call: _e.mock.On("VerifyTOTP", ctx, accountID, code)}
}

func (_c *MFAUsecase_VerifyTOTP_Call) Run(run func(ctx context.Context, accountID string, code string)) *MFAUsecase_VerifyTOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MFAUsecase_VerifyTOTP_Call) Return(_a0 bool, _a1 error) *MFAUsecase_VerifyTOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MFAUsecase_VerifyTOTP_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MFAUsecase_VerifyTOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMFAUsecase creates a new instance of MFAUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMFAUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MFAUsecase {
	mock := &MFAUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
