// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

type NotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationSender) EXPECT() *NotificationSender_Expecter {
	return &NotificationSender_Expecter{mock: &_m.Mock}
}

// SendEmailVerification provides a mock function with given fields: ctx, to, token
func (_m *NotificationSender) SendEmailVerification(ctx context.Context, to string, token string) error {
	ret := _m.Called(ctx, to, token)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationSender_SendEmailVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailVerification'
type NotificationSender_SendEmailVerification_Call struct {
	*mock.Call
}

// SendEmailVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - token string
func (_e *NotificationSender_Expecter) SendEmailVerification(ctx interface{}, to interface{}, token interface{}) *NotificationSender_SendEmailVerification_Call {
	return &NotificationSender_SendEmailVerification_Call{Call: _e.mock.On("SendEmailVerification", ctx, to, token)}
}

func (_c *NotificationSender_SendEmailVerification_Call) Run(run func(ctx context.Context, to string, token string)) *NotificationSender_SendEmailVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationSender_SendEmailVerification_Call) Return(_a0 error) *NotificationSender_SendEmailVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationSender_SendEmailVerification_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationSender_SendEmailVerification_Call {
	_c.Call.Return(run)
	return _c
}

// SendInvitation provides a mock function with given fields: ctx, to, token
func (_m *NotificationSender) SendInvitation(ctx context.Context, to string, token string) error {
	ret := _m.Called(ctx, to, token)

	if len(ret) == 0 {
		panic("no return value specified for SendInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationSender_SendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvitation'
type NotificationSender_SendInvitation_Call struct {
	*mock.Call
}

// SendInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - token string
func (_e *NotificationSender_Expecter) SendInvitation(ctx interface{}, to interface{}, token interface{}) *NotificationSender_SendInvitation_Call {
	return &NotificationSender_SendInvitation_Call{Call: _e.mock.On("SendInvitation", ctx, to, token)}
}

func (_c *NotificationSender_SendInvitation_Call) Run(run func(ctx context.Context, to string, token string)) *NotificationSender_SendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationSender_SendInvitation_Call) Return(_a0 error) *NotificationSender_SendInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationSender_SendInvitation_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationSender_SendInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SendMagicLink provides a mock function with given fields: ctx, to, token
func (_m *NotificationSender) SendMagicLink(ctx context.Context, to string, token string) error {
	ret := _m.Called(ctx, to, token)

	if len(ret) == 0 {
		panic("no return value specified for SendMagicLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationSender_SendMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLink'
type NotificationSender_SendMagicLink_Call struct {
	*mock.Call
}

// SendMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - token string
func (_e *NotificationSender_Expecter) SendMagicLink(ctx interface{}, to interface{}, token interface{}) *NotificationSender_SendMagicLink_Call {
	return &NotificationSender_SendMagicLink_Call{Call: _e.mock.On("SendMagicLink", ctx, to, token)}
}

func (_c *NotificationSender_SendMagicLink_Call) Run(run func(ctx context.Context, to string, token string)) *NotificationSender_SendMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationSender_SendMagicLink_Call) Return(_a0 error) *NotificationSender_SendMagicLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationSender_SendMagicLink_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationSender_SendMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordReset provides a mock function with given fields: ctx, to, token
func (_m *NotificationSender) SendPasswordReset(ctx context.Context, to string, token string) error {
	ret := _m.Called(ctx, to, token)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationSender_SendPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordReset'
type NotificationSender_SendPasswordReset_Call struct {
	*mock.Call
}

// SendPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - token string
func (_e *NotificationSender_Expecter) SendPasswordReset(ctx interface{}, to interface{}, token interface{}) *NotificationSender_SendPasswordReset_Call {
	return &NotificationSender_SendPasswordReset_Call{Call: _e.mock.On("SendPasswordReset", ctx, to, token)}
}

func (_c *NotificationSender_SendPasswordReset_Call) Run(run func(ctx context.Context, to string, token string)) *NotificationSender_SendPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *NotificationSender_SendPasswordReset_Call) Return(_a0 error) *NotificationSender_SendPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationSender_SendPasswordReset_Call) RunAndReturn(run func(context.Context, string, string) error) *NotificationSender_SendPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationSender creates a new instance of NotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSender {
	mock := &NotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
