// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// OrganizationUsecase is an autogenerated mock type for the OrganizationUsecase type
type OrganizationUsecase struct {
	mock.Mock
}

type OrganizationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationUsecase) EXPECT() *OrganizationUsecase_Expecter {
	return &OrganizationUsecase_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, accountID, orgID
func (_m *OrganizationUsecase) Activate(ctx context.Context, accountID string, orgID string) error {
	ret := _m.Called(ctx, accountID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, accountID, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationUsecase_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type OrganizationUsecase_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - orgID string
func (_e *OrganizationUsecase_Expecter) Activate(ctx interface{}, accountID interface{}, orgID interface{}) *OrganizationUsecase_Activate_Call {
	return &OrganizationUsecase_Activate_Call{Call: _e.mock.On("Activate", ctx, accountID, orgID)}
}

func (_c *OrganizationUsecase_Activate_Call) Run(run func(ctx context.Context, accountID string, orgID string)) *OrganizationUsecase_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_Activate_Call) Return(_a0 error) *OrganizationUsecase_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUsecase_Activate_Call) RunAndReturn(run func(context.Context, string, string) error) *OrganizationUsecase_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// ActiveOrg provides a mock function with given fields: ctx, accountID
func (_m *OrganizationUsecase) ActiveOrg(ctx context.Context, accountID string) (string, string, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ActiveOrg")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, accountID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OrganizationUsecase_ActiveOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveOrg'
type OrganizationUsecase_ActiveOrg_Call struct {
	*mock.Call
}

// ActiveOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *OrganizationUsecase_Expecter) ActiveOrg(ctx interface{}, accountID interface{}) *OrganizationUsecase_ActiveOrg_Call {
	return &OrganizationUsecase_ActiveOrg_Call{Call: _e.mock.On("ActiveOrg", ctx, accountID)}
}

func (_c *OrganizationUsecase_ActiveOrg_Call) Run(run func(ctx context.Context, accountID string)) *OrganizationUsecase_ActiveOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_ActiveOrg_Call) Return(orgID string, orgRole string, err error) *OrganizationUsecase_ActiveOrg_Call {
	_c.Call.Return(orgID, orgRole, err)
	return _c
}

func (_c *OrganizationUsecase_ActiveOrg_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *OrganizationUsecase_ActiveOrg_Call {
	_c.Call.Return(run)
	return _c
}

// AddMember provides a mock function with given fields: ctx, orgID, accountID, roleName
func (_m *OrganizationUsecase) AddMember(ctx context.Context, orgID string, accountID string, roleName string) error {
	ret := _m.Called(ctx, orgID, accountID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orgID, accountID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationUsecase_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type OrganizationUsecase_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - accountID string
//   - roleName string
func (_e *OrganizationUsecase_Expecter) AddMember(ctx interface{}, orgID interface{}, accountID interface{}, roleName interface{}) *OrganizationUsecase_AddMember_Call {
	return &OrganizationUsecase_AddMember_Call{Call: _e.mock.On("AddMember", ctx, orgID, accountID, roleName)}
}

func (_c *OrganizationUsecase_AddMember_Call) Run(run func(ctx context.Context, orgID string, accountID string, roleName string)) *OrganizationUsecase_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_AddMember_Call) Return(_a0 error) *OrganizationUsecase_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUsecase_AddMember_Call) RunAndReturn(run func(context.Context, string, string, string) error) *OrganizationUsecase_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, org
func (_m *OrganizationUsecase) Create(ctx context.Context, org domain.Organization) (domain.Organization, error) {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Organization) (domain.Organization, error)); ok {
		return rf(ctx, org)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Organization) domain.Organization); ok {
		r0 = rf(ctx, org)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Organization) error); ok {
		r1 = rf(ctx, org)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrganizationUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org domain.Organization
func (_e *OrganizationUsecase_Expecter) Create(ctx interface{}, org interface{}) *OrganizationUsecase_Create_Call {
	return &OrganizationUsecase_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *OrganizationUsecase_Create_Call) Run(run func(ctx context.Context, org domain.Organization)) *OrganizationUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Organization))
	})
	return _c
}

func (_c *OrganizationUsecase_Create_Call) Return(_a0 domain.Organization, _a1 error) *OrganizationUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Organization) (domain.Organization, error)) *OrganizationUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *OrganizationUsecase) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrganizationUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *OrganizationUsecase_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *OrganizationUsecase_Delete_Call {
	return &OrganizationUsecase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *OrganizationUsecase_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *OrganizationUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *OrganizationUsecase_Delete_Call) Return(_a0 error) *OrganizationUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUsecase_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *OrganizationUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *OrganizationUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Organization, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Organization, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Organization); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrganizationUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *OrganizationUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *OrganizationUsecase_Get_Call {
	return &OrganizationUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *OrganizationUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *OrganizationUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *OrganizationUsecase_Get_Call) Return(_a0 domain.Organization, _a1 error) *OrganizationUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Organization, error)) *OrganizationUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *OrganizationUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Organization], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Organization]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Organization], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Organization]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Organization])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type OrganizationUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *OrganizationUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *OrganizationUsecase_List_Call {
	return &OrganizationUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *OrganizationUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *OrganizationUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *OrganizationUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Organization], _a1 error) *OrganizationUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Organization], error)) *OrganizationUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListForAccount provides a mock function with given fields: ctx, accountID
func (_m *OrganizationUsecase) ListForAccount(ctx context.Context, accountID string) ([]domain.Organization, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ListForAccount")
	}

	var r0 []domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Organization, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Organization); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_ListForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForAccount'
type OrganizationUsecase_ListForAccount_Call struct {
	*mock.Call
}

// ListForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *OrganizationUsecase_Expecter) ListForAccount(ctx interface{}, accountID interface{}) *OrganizationUsecase_ListForAccount_Call {
	return &OrganizationUsecase_ListForAccount_Call{Call: _e.mock.On("ListForAccount", ctx, accountID)}
}

func (_c *OrganizationUsecase_ListForAccount_Call) Run(run func(ctx context.Context, accountID string)) *OrganizationUsecase_ListForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_ListForAccount_Call) Return(_a0 []domain.Organization, _a1 error) *OrganizationUsecase_ListForAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_ListForAccount_Call) RunAndReturn(run func(context.Context, string) ([]domain.Organization, error)) *OrganizationUsecase_ListForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, orgID
func (_m *OrganizationUsecase) ListMembers(ctx context.Context, orgID string) ([]domain.Binding, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []domain.Binding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Binding, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Binding); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Binding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type OrganizationUsecase_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *OrganizationUsecase_Expecter) ListMembers(ctx interface{}, orgID interface{}) *OrganizationUsecase_ListMembers_Call {
	return &OrganizationUsecase_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, orgID)}
}

func (_c *OrganizationUsecase_ListMembers_Call) Run(run func(ctx context.Context, orgID string)) *OrganizationUsecase_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_ListMembers_Call) Return(_a0 []domain.Binding, _a1 error) *OrganizationUsecase_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_ListMembers_Call) RunAndReturn(run func(context.Context, string) ([]domain.Binding, error)) *OrganizationUsecase_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: _a0, _a1
func (_m *OrganizationUsecase) Patch(_a0 context.Context, _a1 ...repository.PatchOption) ([]domain.Organization, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 []domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) ([]domain.Organization, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) []domain.Organization); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...repository.PatchOption) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationUsecase_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type OrganizationUsecase_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...repository.PatchOption
func (_e *OrganizationUsecase_Expecter) Patch(_a0 interface{}, _a1 ...interface{}) *OrganizationUsecase_Patch_Call {
	return &OrganizationUsecase_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *OrganizationUsecase_Patch_Call) Run(run func(_a0 context.Context, _a1 ...repository.PatchOption)) *OrganizationUsecase_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repository.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(repository.PatchOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *OrganizationUsecase_Patch_Call) Return(_a0 []domain.Organization, _a1 error) *OrganizationUsecase_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationUsecase_Patch_Call) RunAndReturn(run func(context.Context, ...repository.PatchOption) ([]domain.Organization, error)) *OrganizationUsecase_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, accountID
func (_m *OrganizationUsecase) RemoveMember(ctx context.Context, orgID string, accountID string) error {
	ret := _m.Called(ctx, orgID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationUsecase_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type OrganizationUsecase_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - accountID string
func (_e *OrganizationUsecase_Expecter) RemoveMember(ctx interface{}, orgID interface{}, accountID interface{}) *OrganizationUsecase_RemoveMember_Call {
	return &OrganizationUsecase_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, accountID)}
}

func (_c *OrganizationUsecase_RemoveMember_Call) Run(run func(ctx context.Context, orgID string, accountID string)) *OrganizationUsecase_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrganizationUsecase_RemoveMember_Call) Return(_a0 error) *OrganizationUsecase_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationUsecase_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *OrganizationUsecase_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationUsecase creates a new instance of OrganizationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationUsecase {
	mock := &OrganizationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
