// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PasswordResetUsecase is an autogenerated mock type for the PasswordResetUsecase type
type PasswordResetUsecase struct {
	mock.Mock
}

type PasswordResetUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordResetUsecase) EXPECT() *PasswordResetUsecase_Expecter {
	return &PasswordResetUsecase_Expecter{mock: &_m.Mock}
}

// ConfirmPasswordReset provides a mock function with given fields: ctx, token, newPassword
func (_m *PasswordResetUsecase) ConfirmPasswordReset(ctx context.Context, token string, newPassword string) error {
	ret := _m.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordResetUsecase_ConfirmPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPasswordReset'
type PasswordResetUsecase_ConfirmPasswordReset_Call struct {
	*mock.Call
}

// ConfirmPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *PasswordResetUsecase_Expecter) ConfirmPasswordReset(ctx interface{}, token interface{}, newPassword interface{}) *PasswordResetUsecase_ConfirmPasswordReset_Call {
	return &PasswordResetUsecase_ConfirmPasswordReset_Call{Call: _e.mock.On("ConfirmPasswordReset", ctx, token, newPassword)}
}

func (_c *PasswordResetUsecase_ConfirmPasswordReset_Call) Run(run func(ctx context.Context, token string, newPassword string)) *PasswordResetUsecase_ConfirmPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PasswordResetUsecase_ConfirmPasswordReset_Call) Return(_a0 error) *PasswordResetUsecase_ConfirmPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordResetUsecase_ConfirmPasswordReset_Call) RunAndReturn(run func(context.Context, string, string) error) *PasswordResetUsecase_ConfirmPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, realmID, email
func (_m *PasswordResetUsecase) RequestPasswordReset(ctx context.Context, realmID string, email string) error {
	ret := _m.Called(ctx, realmID, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, realmID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordResetUsecase_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type PasswordResetUsecase_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - email string
func (_e *PasswordResetUsecase_Expecter) RequestPasswordReset(ctx interface{}, realmID interface{}, email interface{}) *PasswordResetUsecase_RequestPasswordReset_Call {
	return &PasswordResetUsecase_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, realmID, email)}
}

func (_c *PasswordResetUsecase_RequestPasswordReset_Call) Run(run func(ctx context.Context, realmID string, email string)) *PasswordResetUsecase_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PasswordResetUsecase_RequestPasswordReset_Call) Return(_a0 error) *PasswordResetUsecase_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordResetUsecase_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string, string) error) *PasswordResetUsecase_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordResetUsecase creates a new instance of PasswordResetUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordResetUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordResetUsecase {
	mock := &PasswordResetUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
