// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

type PermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionRepository) EXPECT() *PermissionRepository_Expecter {
	return &PermissionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *PermissionRepository) Create(_a0 context.Context, _a1 domain.Permission) (domain.Permission, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Permission) (domain.Permission, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Permission) domain.Permission); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Permission) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermissionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PermissionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Permission
func (_e *PermissionRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *PermissionRepository_Create_Call {
	return &PermissionRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *PermissionRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.Permission)) *PermissionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Permission))
	})
	return _c
}

func (_c *PermissionRepository_Create_Call) Return(_a0 domain.Permission, _a1 error) *PermissionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PermissionRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Permission) (domain.Permission, error)) *PermissionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *PermissionRepository) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PermissionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PermissionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *PermissionRepository_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *PermissionRepository_Delete_Call {
	return &PermissionRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *PermissionRepository_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *PermissionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *PermissionRepository_Delete_Call) Return(_a0 error) *PermissionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PermissionRepository_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *PermissionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *PermissionRepository) Get(ctx context.Context, opts ...search.Option) (domain.Permission, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Permission, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Permission); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermissionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PermissionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *PermissionRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *PermissionRepository_Get_Call {
	return &PermissionRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *PermissionRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *PermissionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PermissionRepository_Get_Call) Return(_a0 domain.Permission, _a1 error) *PermissionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PermissionRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Permission, error)) *PermissionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *PermissionRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Permission], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Permission]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Permission], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Permission]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Permission])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermissionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PermissionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *PermissionRepository_Expecter) List(ctx interface{}, opts ...interface{}) *PermissionRepository_List_Call {
	return &PermissionRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *PermissionRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *PermissionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PermissionRepository_List_Call) Return(_a0 resource.ListResponse[domain.Permission], _a1 error) *PermissionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PermissionRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Permission], error)) *PermissionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
