// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PreferenceUsecase is an autogenerated mock type for the PreferenceUsecase type
type PreferenceUsecase struct {
	mock.Mock
}

type PreferenceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *PreferenceUsecase) EXPECT() *PreferenceUsecase_Expecter {
	return &PreferenceUsecase_Expecter{mock: &_m.Mock}
}

// Claims provides a mock function with given fields: ctx, accountID
func (_m *PreferenceUsecase) Claims(ctx context.Context, accountID string) (map[string]string, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Claims")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreferenceUsecase_Claims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claims'
type PreferenceUsecase_Claims_Call struct {
	*mock.Call
}

// Claims is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *PreferenceUsecase_Expecter) Claims(ctx interface{}, accountID interface{}) *PreferenceUsecase_Claims_Call {
	return &PreferenceUsecase_Claims_Call{Call: _e.mock.On("Claims", ctx, accountID)}
}

func (_c *PreferenceUsecase_Claims_Call) Run(run func(ctx context.Context, accountID string)) *PreferenceUsecase_Claims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PreferenceUsecase_Claims_Call) Return(_a0 map[string]string, _a1 error) *PreferenceUsecase_Claims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreferenceUsecase_Claims_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *PreferenceUsecase_Claims_Call {
	_c.Call.Return(run)
	return _c
}

// ResetForAccount provides a mock function with given fields: ctx, accountID, keys
func (_m *PreferenceUsecase) ResetForAccount(ctx context.Context, accountID string, keys []string) error {
	ret := _m.Called(ctx, accountID, keys)

	if len(ret) == 0 {
		panic("no return value specified for ResetForAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, accountID, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceUsecase_ResetForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetForAccount'
type PreferenceUsecase_ResetForAccount_Call struct {
	*mock.Call
}

// ResetForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - keys []string
func (_e *PreferenceUsecase_Expecter) ResetForAccount(ctx interface{}, accountID interface{}, keys interface{}) *PreferenceUsecase_ResetForAccount_Call {
	return &PreferenceUsecase_ResetForAccount_Call{Call: _e.mock.On("ResetForAccount", ctx, accountID, keys)}
}

func (_c *PreferenceUsecase_ResetForAccount_Call) Run(run func(ctx context.Context, accountID string, keys []string)) *PreferenceUsecase_ResetForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *PreferenceUsecase_ResetForAccount_Call) Return(_a0 error) *PreferenceUsecase_ResetForAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceUsecase_ResetForAccount_Call) RunAndReturn(run func(context.Context, string, []string) error) *PreferenceUsecase_ResetForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, accountID, keys
func (_m *PreferenceUsecase) Resolve(ctx context.Context, accountID string, keys []string) ([]domain.Preference, error) {
	ret := _m.Called(ctx, accountID, keys)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []domain.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]domain.Preference, error)); ok {
		return rf(ctx, accountID, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []domain.Preference); ok {
		r0 = rf(ctx, accountID, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Preference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, accountID, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreferenceUsecase_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type PreferenceUsecase_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - keys []string
func (_e *PreferenceUsecase_Expecter) Resolve(ctx interface{}, accountID interface{}, keys interface{}) *PreferenceUsecase_Resolve_Call {
	return &PreferenceUsecase_Resolve_Call{Call: _e.mock.On("Resolve", ctx, accountID, keys)}
}

func (_c *PreferenceUsecase_Resolve_Call) Run(run func(ctx context.Context, accountID string, keys []string)) *PreferenceUsecase_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *PreferenceUsecase_Resolve_Call) Return(_a0 []domain.Preference, _a1 error) *PreferenceUsecase_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreferenceUsecase_Resolve_Call) RunAndReturn(run func(context.Context, string, []string) ([]domain.Preference, error)) *PreferenceUsecase_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// SetForAccount provides a mock function with given fields: ctx, accountID, values
func (_m *PreferenceUsecase) SetForAccount(ctx context.Context, accountID string, values map[string]string) error {
	ret := _m.Called(ctx, accountID, values)

	if len(ret) == 0 {
		panic("no return value specified for SetForAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, accountID, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceUsecase_SetForAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetForAccount'
type PreferenceUsecase_SetForAccount_Call struct {
	*mock.Call
}

// SetForAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - values map[string]string
func (_e *PreferenceUsecase_Expecter) SetForAccount(ctx interface{}, accountID interface{}, values interface{}) *PreferenceUsecase_SetForAccount_Call {
	return &PreferenceUsecase_SetForAccount_Call{Call: _e.mock.On("SetForAccount", ctx, accountID, values)}
}

func (_c *PreferenceUsecase_SetForAccount_Call) Run(run func(ctx context.Context, accountID string, values map[string]string)) *PreferenceUsecase_SetForAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *PreferenceUsecase_SetForAccount_Call) Return(_a0 error) *PreferenceUsecase_SetForAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceUsecase_SetForAccount_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *PreferenceUsecase_SetForAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetForOrganization provides a mock function with given fields: ctx, orgID, values
func (_m *PreferenceUsecase) SetForOrganization(ctx context.Context, orgID string, values map[string]string) error {
	ret := _m.Called(ctx, orgID, values)

	if len(ret) == 0 {
		panic("no return value specified for SetForOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, orgID, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceUsecase_SetForOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetForOrganization'
type PreferenceUsecase_SetForOrganization_Call struct {
	*mock.Call
}

// SetForOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - values map[string]string
func (_e *PreferenceUsecase_Expecter) SetForOrganization(ctx interface{}, orgID interface{}, values interface{}) *PreferenceUsecase_SetForOrganization_Call {
	return &PreferenceUsecase_SetForOrganization_Call{Call: _e.mock.On("SetForOrganization", ctx, orgID, values)}
}

func (_c *PreferenceUsecase_SetForOrganization_Call) Run(run func(ctx context.Context, orgID string, values map[string]string)) *PreferenceUsecase_SetForOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *PreferenceUsecase_SetForOrganization_Call) Return(_a0 error) *PreferenceUsecase_SetForOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceUsecase_SetForOrganization_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *PreferenceUsecase_SetForOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreferenceUsecase creates a new instance of PreferenceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreferenceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreferenceUsecase {
	mock := &PreferenceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
