// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PreferenceStore is an autogenerated mock type for the PreferenceStore type
type PreferenceStore struct {
	mock.Mock
}

type PreferenceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PreferenceStore) EXPECT() *PreferenceStore_Expecter {
	return &PreferenceStore_Expecter{mock: &_m.Mock}
}

// AccountPreferences provides a mock function with given fields: ctx, accountID, keys
func (_m *PreferenceStore) AccountPreferences(ctx context.Context, accountID string, keys []string) (map[string]string, error) {
	ret := _m.Called(ctx, accountID, keys)

	if len(ret) == 0 {
		panic("no return value specified for AccountPreferences")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]string, error)); ok {
		return rf(ctx, accountID, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) map[string]string); ok {
		r0 = rf(ctx, accountID, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, accountID, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreferenceStore_AccountPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountPreferences'
type PreferenceStore_AccountPreferences_Call struct {
	*mock.Call
}

// AccountPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - keys []string
func (_e *PreferenceStore_Expecter) AccountPreferences(ctx interface{}, accountID interface{}, keys interface{}) *PreferenceStore_AccountPreferences_Call {
	return &PreferenceStore_AccountPreferences_Call{Call: _e.mock.On("AccountPreferences", ctx, accountID, keys)}
}

func (_c *PreferenceStore_AccountPreferences_Call) Run(run func(ctx context.Context, accountID string, keys []string)) *PreferenceStore_AccountPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *PreferenceStore_AccountPreferences_Call) Return(_a0 map[string]string, _a1 error) *PreferenceStore_AccountPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreferenceStore_AccountPreferences_Call) RunAndReturn(run func(context.Context, string, []string) (map[string]string, error)) *PreferenceStore_AccountPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccountPreferences provides a mock function with given fields: ctx, accountID, keys
func (_m *PreferenceStore) DeleteAccountPreferences(ctx context.Context, accountID string, keys []string) error {
	ret := _m.Called(ctx, accountID, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccountPreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, accountID, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceStore_DeleteAccountPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccountPreferences'
type PreferenceStore_DeleteAccountPreferences_Call struct {
	*mock.Call
}

// DeleteAccountPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - keys []string
func (_e *PreferenceStore_Expecter) DeleteAccountPreferences(ctx interface{}, accountID interface{}, keys interface{}) *PreferenceStore_DeleteAccountPreferences_Call {
	return &PreferenceStore_DeleteAccountPreferences_Call{Call: _e.mock.On("DeleteAccountPreferences", ctx, accountID, keys)}
}

func (_c *PreferenceStore_DeleteAccountPreferences_Call) Run(run func(ctx context.Context, accountID string, keys []string)) *PreferenceStore_DeleteAccountPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *PreferenceStore_DeleteAccountPreferences_Call) Return(_a0 error) *PreferenceStore_DeleteAccountPreferences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceStore_DeleteAccountPreferences_Call) RunAndReturn(run func(context.Context, string, []string) error) *PreferenceStore_DeleteAccountPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// OrganizationPreferences provides a mock function with given fields: ctx, orgID, keys
func (_m *PreferenceStore) OrganizationPreferences(ctx context.Context, orgID string, keys []string) (map[string]string, error) {
	ret := _m.Called(ctx, orgID, keys)

	if len(ret) == 0 {
		panic("no return value specified for OrganizationPreferences")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]string, error)); ok {
		return rf(ctx, orgID, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) map[string]string); ok {
		r0 = rf(ctx, orgID, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, orgID, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreferenceStore_OrganizationPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrganizationPreferences'
type PreferenceStore_OrganizationPreferences_Call struct {
	*mock.Call
}

// OrganizationPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - keys []string
func (_e *PreferenceStore_Expecter) OrganizationPreferences(ctx interface{}, orgID interface{}, keys interface{}) *PreferenceStore_OrganizationPreferences_Call {
	return &PreferenceStore_OrganizationPreferences_Call{Call: _e.mock.On("OrganizationPreferences", ctx, orgID, keys)}
}

func (_c *PreferenceStore_OrganizationPreferences_Call) Run(run func(ctx context.Context, orgID string, keys []string)) *PreferenceStore_OrganizationPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *PreferenceStore_OrganizationPreferences_Call) Return(_a0 map[string]string, _a1 error) *PreferenceStore_OrganizationPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreferenceStore_OrganizationPreferences_Call) RunAndReturn(run func(context.Context, string, []string) (map[string]string, error)) *PreferenceStore_OrganizationPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccountPreferences provides a mock function with given fields: ctx, accountID, values
func (_m *PreferenceStore) SetAccountPreferences(ctx context.Context, accountID string, values map[string]string) error {
	ret := _m.Called(ctx, accountID, values)

	if len(ret) == 0 {
		panic("no return value specified for SetAccountPreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, accountID, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceStore_SetAccountPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccountPreferences'
type PreferenceStore_SetAccountPreferences_Call struct {
	*mock.Call
}

// SetAccountPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - values map[string]string
func (_e *PreferenceStore_Expecter) SetAccountPreferences(ctx interface{}, accountID interface{}, values interface{}) *PreferenceStore_SetAccountPreferences_Call {
	return &PreferenceStore_SetAccountPreferences_Call{Call: _e.mock.On("SetAccountPreferences", ctx, accountID, values)}
}

func (_c *PreferenceStore_SetAccountPreferences_Call) Run(run func(ctx context.Context, accountID string, values map[string]string)) *PreferenceStore_SetAccountPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *PreferenceStore_SetAccountPreferences_Call) Return(_a0 error) *PreferenceStore_SetAccountPreferences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceStore_SetAccountPreferences_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *PreferenceStore_SetAccountPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrganizationPreferences provides a mock function with given fields: ctx, orgID, values
func (_m *PreferenceStore) SetOrganizationPreferences(ctx context.Context, orgID string, values map[string]string) error {
	ret := _m.Called(ctx, orgID, values)

	if len(ret) == 0 {
		panic("no return value specified for SetOrganizationPreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, orgID, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceStore_SetOrganizationPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrganizationPreferences'
type PreferenceStore_SetOrganizationPreferences_Call struct {
	*mock.Call
}

// SetOrganizationPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - values map[string]string
func (_e *PreferenceStore_Expecter) SetOrganizationPreferences(ctx interface{}, orgID interface{}, values interface{}) *PreferenceStore_SetOrganizationPreferences_Call {
	return &PreferenceStore_SetOrganizationPreferences_Call{Call: _e.mock.On("SetOrganizationPreferences", ctx, orgID, values)}
}

func (_c *PreferenceStore_SetOrganizationPreferences_Call) Run(run func(ctx context.Context, orgID string, values map[string]string)) *PreferenceStore_SetOrganizationPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *PreferenceStore_SetOrganizationPreferences_Call) Return(_a0 error) *PreferenceStore_SetOrganizationPreferences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceStore_SetOrganizationPreferences_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *PreferenceStore_SetOrganizationPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreferenceStore creates a new instance of PreferenceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreferenceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreferenceStore {
	mock := &PreferenceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
