// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"
	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProfileUsecase is an autogenerated mock type for the ProfileUsecase type
type ProfileUsecase struct {
	mock.Mock
}

type ProfileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileUsecase) EXPECT() *ProfileUsecase_Expecter {
	return &ProfileUsecase_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, in
func (_m *ProfileUsecase) ChangePassword(ctx context.Context, in app.ChangePasswordInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, app.ChangePasswordInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileUsecase_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type ProfileUsecase_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - in app.ChangePasswordInput
func (_e *ProfileUsecase_Expecter) ChangePassword(ctx interface{}, in interface{}) *ProfileUsecase_ChangePassword_Call {
	return &ProfileUsecase_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, in)}
}

func (_c *ProfileUsecase_ChangePassword_Call) Run(run func(ctx context.Context, in app.ChangePasswordInput)) *ProfileUsecase_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.ChangePasswordInput))
	})
	return _c
}

func (_c *ProfileUsecase_ChangePassword_Call) Return(_a0 error) *ProfileUsecase_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileUsecase_ChangePassword_Call) RunAndReturn(run func(context.Context, app.ChangePasswordInput) error) *ProfileUsecase_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Profile provides a mock function with given fields: ctx, accountID
func (_m *ProfileUsecase) Profile(ctx context.Context, accountID string) (domain.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Profile")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileUsecase_Profile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Profile'
type ProfileUsecase_Profile_Call struct {
	*mock.Call
}

// Profile is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *ProfileUsecase_Expecter) Profile(ctx interface{}, accountID interface{}) *ProfileUsecase_Profile_Call {
	return &ProfileUsecase_Profile_Call{Call: _e.mock.On("Profile", ctx, accountID)}
}

func (_c *ProfileUsecase_Profile_Call) Run(run func(ctx context.Context, accountID string)) *ProfileUsecase_Profile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProfileUsecase_Profile_Call) Return(_a0 domain.Account, _a1 error) *ProfileUsecase_Profile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileUsecase_Profile_Call) RunAndReturn(run func(context.Context, string) (domain.Account, error)) *ProfileUsecase_Profile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, in
func (_m *ProfileUsecase) UpdateProfile(ctx context.Context, in app.UpdateProfileInput) (domain.Account, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, app.UpdateProfileInput) (domain.Account, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, app.UpdateProfileInput) domain.Account); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, app.UpdateProfileInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileUsecase_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type ProfileUsecase_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - in app.UpdateProfileInput
func (_e *ProfileUsecase_Expecter) UpdateProfile(ctx interface{}, in interface{}) *ProfileUsecase_UpdateProfile_Call {
	return &ProfileUsecase_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, in)}
}

func (_c *ProfileUsecase_UpdateProfile_Call) Run(run func(ctx context.Context, in app.UpdateProfileInput)) *ProfileUsecase_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.UpdateProfileInput))
	})
	return _c
}

func (_c *ProfileUsecase_UpdateProfile_Call) Return(_a0 domain.Account, _a1 error) *ProfileUsecase_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileUsecase_UpdateProfile_Call) RunAndReturn(run func(context.Context, app.UpdateProfileInput) (domain.Account, error)) *ProfileUsecase_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewProfileUsecase creates a new instance of ProfileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileUsecase {
	mock := &ProfileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
