// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RealmACRPolicyRepository is an autogenerated mock type for the RealmACRPolicyRepository type
type RealmACRPolicyRepository struct {
	mock.Mock
}

type RealmACRPolicyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RealmACRPolicyRepository) EXPECT() *RealmACRPolicyRepository_Expecter {
	return &RealmACRPolicyRepository_Expecter{mock: &_m.Mock}
}

// GetByRealm provides a mock function with given fields: ctx, realmID
func (_m *RealmACRPolicyRepository) GetByRealm(ctx context.Context, realmID string) (domain.RealmACRPolicy, error) {
	ret := _m.Called(ctx, realmID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRealm")
	}

	var r0 domain.RealmACRPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.RealmACRPolicy, error)); ok {
		return rf(ctx, realmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.RealmACRPolicy); ok {
		r0 = rf(ctx, realmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.RealmACRPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, realmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmACRPolicyRepository_GetByRealm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRealm'
type RealmACRPolicyRepository_GetByRealm_Call struct {
	*mock.Call
}

// GetByRealm is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
func (_e *RealmACRPolicyRepository_Expecter) GetByRealm(ctx interface{}, realmID interface{}) *RealmACRPolicyRepository_GetByRealm_Call {
	return &RealmACRPolicyRepository_GetByRealm_Call{Call: _e.mock.On("GetByRealm", ctx, realmID)}
}

func (_c *RealmACRPolicyRepository_GetByRealm_Call) Run(run func(ctx context.Context, realmID string)) *RealmACRPolicyRepository_GetByRealm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RealmACRPolicyRepository_GetByRealm_Call) Return(_a0 domain.RealmACRPolicy, _a1 error) *RealmACRPolicyRepository_GetByRealm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmACRPolicyRepository_GetByRealm_Call) RunAndReturn(run func(context.Context, string) (domain.RealmACRPolicy, error)) *RealmACRPolicyRepository_GetByRealm_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, p
func (_m *RealmACRPolicyRepository) Upsert(ctx context.Context, p domain.RealmACRPolicy) (domain.RealmACRPolicy, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.RealmACRPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RealmACRPolicy) (domain.RealmACRPolicy, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RealmACRPolicy) domain.RealmACRPolicy); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.RealmACRPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RealmACRPolicy) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmACRPolicyRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type RealmACRPolicyRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.RealmACRPolicy
func (_e *RealmACRPolicyRepository_Expecter) Upsert(ctx interface{}, p interface{}) *RealmACRPolicyRepository_Upsert_Call {
	return &RealmACRPolicyRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, p)}
}

func (_c *RealmACRPolicyRepository_Upsert_Call) Run(run func(ctx context.Context, p domain.RealmACRPolicy)) *RealmACRPolicyRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RealmACRPolicy))
	})
	return _c
}

func (_c *RealmACRPolicyRepository_Upsert_Call) Return(_a0 domain.RealmACRPolicy, _a1 error) *RealmACRPolicyRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmACRPolicyRepository_Upsert_Call) RunAndReturn(run func(context.Context, domain.RealmACRPolicy) (domain.RealmACRPolicy, error)) *RealmACRPolicyRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewRealmACRPolicyRepository creates a new instance of RealmACRPolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealmACRPolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealmACRPolicyRepository {
	mock := &RealmACRPolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
