// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// RealmUsecase is an autogenerated mock type for the RealmUsecase type
type RealmUsecase struct {
	mock.Mock
}

type RealmUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *RealmUsecase) EXPECT() *RealmUsecase_Expecter {
	return &RealmUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, realm
func (_m *RealmUsecase) Create(ctx context.Context, realm domain.Realm) (domain.Realm, error) {
	ret := _m.Called(ctx, realm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Realm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Realm) (domain.Realm, error)); ok {
		return rf(ctx, realm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Realm) domain.Realm); ok {
		r0 = rf(ctx, realm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Realm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Realm) error); ok {
		r1 = rf(ctx, realm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RealmUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - realm domain.Realm
func (_e *RealmUsecase_Expecter) Create(ctx interface{}, realm interface{}) *RealmUsecase_Create_Call {
	return &RealmUsecase_Create_Call{Call: _e.mock.On("Create", ctx, realm)}
}

func (_c *RealmUsecase_Create_Call) Run(run func(ctx context.Context, realm domain.Realm)) *RealmUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Realm))
	})
	return _c
}

func (_c *RealmUsecase_Create_Call) Return(_a0 domain.Realm, _a1 error) *RealmUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Realm) (domain.Realm, error)) *RealmUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *RealmUsecase) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RealmUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RealmUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *RealmUsecase_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *RealmUsecase_Delete_Call {
	return &RealmUsecase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *RealmUsecase_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *RealmUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *RealmUsecase_Delete_Call) Return(_a0 error) *RealmUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RealmUsecase_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *RealmUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *RealmUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Realm, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Realm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Realm, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Realm); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Realm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RealmUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *RealmUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *RealmUsecase_Get_Call {
	return &RealmUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *RealmUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *RealmUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RealmUsecase_Get_Call) Return(_a0 domain.Realm, _a1 error) *RealmUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Realm, error)) *RealmUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *RealmUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Realm], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Realm]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Realm], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Realm]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Realm])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RealmUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *RealmUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *RealmUsecase_List_Call {
	return &RealmUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *RealmUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *RealmUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RealmUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Realm], _a1 error) *RealmUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Realm], error)) *RealmUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: _a0, _a1
func (_m *RealmUsecase) Patch(_a0 context.Context, _a1 ...repository.PatchOption) ([]domain.Realm, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 []domain.Realm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) ([]domain.Realm, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) []domain.Realm); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Realm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...repository.PatchOption) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RealmUsecase_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type RealmUsecase_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...repository.PatchOption
func (_e *RealmUsecase_Expecter) Patch(_a0 interface{}, _a1 ...interface{}) *RealmUsecase_Patch_Call {
	return &RealmUsecase_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *RealmUsecase_Patch_Call) Run(run func(_a0 context.Context, _a1 ...repository.PatchOption)) *RealmUsecase_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repository.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(repository.PatchOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RealmUsecase_Patch_Call) Return(_a0 []domain.Realm, _a1 error) *RealmUsecase_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RealmUsecase_Patch_Call) RunAndReturn(run func(context.Context, ...repository.PatchOption) ([]domain.Realm, error)) *RealmUsecase_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// NewRealmUsecase creates a new instance of RealmUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealmUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealmUsecase {
	mock := &RealmUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
