// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RecoveryCodeRepository is an autogenerated mock type for the RecoveryCodeRepository type
type RecoveryCodeRepository struct {
	mock.Mock
}

type RecoveryCodeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RecoveryCodeRepository) EXPECT() *RecoveryCodeRepository_Expecter {
	return &RecoveryCodeRepository_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, accountID, codeHash, at
func (_m *RecoveryCodeRepository) Consume(ctx context.Context, accountID string, codeHash string, at time.Time) (bool, error) {
	ret := _m.Called(ctx, accountID, codeHash, at)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (bool, error)); ok {
		return rf(ctx, accountID, codeHash, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) bool); ok {
		r0 = rf(ctx, accountID, codeHash, at)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, accountID, codeHash, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecoveryCodeRepository_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type RecoveryCodeRepository_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - codeHash string
//   - at time.Time
func (_e *RecoveryCodeRepository_Expecter) Consume(ctx interface{}, accountID interface{}, codeHash interface{}, at interface{}) *RecoveryCodeRepository_Consume_Call {
	return &RecoveryCodeRepository_Consume_Call{Call: _e.mock.On("Consume", ctx, accountID, codeHash, at)}
}

func (_c *RecoveryCodeRepository_Consume_Call) Run(run func(ctx context.Context, accountID string, codeHash string, at time.Time)) *RecoveryCodeRepository_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *RecoveryCodeRepository_Consume_Call) Return(_a0 bool, _a1 error) *RecoveryCodeRepository_Consume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecoveryCodeRepository_Consume_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (bool, error)) *RecoveryCodeRepository_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: ctx, accountID, codeHashes
func (_m *RecoveryCodeRepository) CreateMany(ctx context.Context, accountID string, codeHashes []string) error {
	ret := _m.Called(ctx, accountID, codeHashes)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, accountID, codeHashes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecoveryCodeRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type RecoveryCodeRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - codeHashes []string
func (_e *RecoveryCodeRepository_Expecter) CreateMany(ctx interface{}, accountID interface{}, codeHashes interface{}) *RecoveryCodeRepository_CreateMany_Call {
	return &RecoveryCodeRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, accountID, codeHashes)}
}

func (_c *RecoveryCodeRepository_CreateMany_Call) Run(run func(ctx context.Context, accountID string, codeHashes []string)) *RecoveryCodeRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *RecoveryCodeRepository_CreateMany_Call) Return(_a0 error) *RecoveryCodeRepository_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecoveryCodeRepository_CreateMany_Call) RunAndReturn(run func(context.Context, string, []string) error) *RecoveryCodeRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAccount provides a mock function with given fields: ctx, accountID
func (_m *RecoveryCodeRepository) DeleteByAccount(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecoveryCodeRepository_DeleteByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAccount'
type RecoveryCodeRepository_DeleteByAccount_Call struct {
	*mock.Call
}

// DeleteByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *RecoveryCodeRepository_Expecter) DeleteByAccount(ctx interface{}, accountID interface{}) *RecoveryCodeRepository_DeleteByAccount_Call {
	return &RecoveryCodeRepository_DeleteByAccount_Call{Call: _e.mock.On("DeleteByAccount", ctx, accountID)}
}

func (_c *RecoveryCodeRepository_DeleteByAccount_Call) Run(run func(ctx context.Context, accountID string)) *RecoveryCodeRepository_DeleteByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecoveryCodeRepository_DeleteByAccount_Call) Return(_a0 error) *RecoveryCodeRepository_DeleteByAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecoveryCodeRepository_DeleteByAccount_Call) RunAndReturn(run func(context.Context, string) error) *RecoveryCodeRepository_DeleteByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecoveryCodeRepository creates a new instance of RecoveryCodeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecoveryCodeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecoveryCodeRepository {
	mock := &RecoveryCodeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
