// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *RefreshTokenRepository) Create(ctx context.Context, token domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token domain.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(_a0 error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, domain.RefreshToken) error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, hash
func (_m *RefreshTokenRepository) GetByHash(ctx context.Context, hash string) (domain.RefreshToken, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.RefreshToken, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.RefreshToken); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(domain.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type RefreshTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *RefreshTokenRepository_Expecter) GetByHash(ctx interface{}, hash interface{}) *RefreshTokenRepository_GetByHash_Call {
	return &RefreshTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *RefreshTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *RefreshTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_GetByHash_Call) Return(_a0 domain.RefreshToken, _a1 error) *RefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (domain.RefreshToken, error)) *RefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, id, now
func (_m *RefreshTokenRepository) MarkUsed(ctx context.Context, id string, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type RefreshTokenRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - now time.Time
func (_e *RefreshTokenRepository_Expecter) MarkUsed(ctx interface{}, id interface{}, now interface{}) *RefreshTokenRepository_MarkUsed_Call {
	return &RefreshTokenRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id, now)}
}

func (_c *RefreshTokenRepository_MarkUsed_Call) Run(run func(ctx context.Context, id string, now time.Time)) *RefreshTokenRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *RefreshTokenRepository_MarkUsed_Call) Return(_a0 bool, _a1 error) *RefreshTokenRepository_MarkUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, string, time.Time) (bool, error)) *RefreshTokenRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
