// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	domain "github.com/fromforgesoftware/aegis/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RiskUsecase is an autogenerated mock type for the RiskUsecase type
type RiskUsecase struct {
	mock.Mock
}

type RiskUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *RiskUsecase) EXPECT() *RiskUsecase_Expecter {
	return &RiskUsecase_Expecter{mock: &_m.Mock}
}

// Assess provides a mock function with given fields: ctx, in
func (_m *RiskUsecase) Assess(ctx context.Context, in app.RiskInput) (domain.RiskAssessment, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Assess")
	}

	var r0 domain.RiskAssessment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, app.RiskInput) (domain.RiskAssessment, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, app.RiskInput) domain.RiskAssessment); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.RiskAssessment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, app.RiskInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RiskUsecase_Assess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assess'
type RiskUsecase_Assess_Call struct {
	*mock.Call
}

// Assess is a helper method to define mock.On call
//   - ctx context.Context
//   - in app.RiskInput
func (_e *RiskUsecase_Expecter) Assess(ctx interface{}, in interface{}) *RiskUsecase_Assess_Call {
	return &RiskUsecase_Assess_Call{Call: _e.mock.On("Assess", ctx, in)}
}

func (_c *RiskUsecase_Assess_Call) Run(run func(ctx context.Context, in app.RiskInput)) *RiskUsecase_Assess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.RiskInput))
	})
	return _c
}

func (_c *RiskUsecase_Assess_Call) Return(_a0 domain.RiskAssessment, _a1 error) *RiskUsecase_Assess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RiskUsecase_Assess_Call) RunAndReturn(run func(context.Context, app.RiskInput) (domain.RiskAssessment, error)) *RiskUsecase_Assess_Call {
	_c.Call.Return(run)
	return _c
}

// NewRiskUsecase creates a new instance of RiskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskUsecase {
	mock := &RiskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
