// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RoleResolver is an autogenerated mock type for the RoleResolver type
type RoleResolver struct {
	mock.Mock
}

type RoleResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleResolver) EXPECT() *RoleResolver_Expecter {
	return &RoleResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx
func (_m *RoleResolver) Resolve(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type RoleResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleResolver_Expecter) Resolve(ctx interface{}) *RoleResolver_Resolve_Call {
	return &RoleResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx)}
}

func (_c *RoleResolver_Resolve_Call) Run(run func(ctx context.Context)) *RoleResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RoleResolver_Resolve_Call) Return(_a0 error) *RoleResolver_Resolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleResolver_Resolve_Call) RunAndReturn(run func(context.Context) error) *RoleResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewRoleResolver creates a new instance of RoleResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleResolver {
	mock := &RoleResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
