// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// RoleUsecase is an autogenerated mock type for the RoleUsecase type
type RoleUsecase struct {
	mock.Mock
}

type RoleUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleUsecase) EXPECT() *RoleUsecase_Expecter {
	return &RoleUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role, permissionIDs
func (_m *RoleUsecase) Create(ctx context.Context, role domain.Role, permissionIDs []string) (domain.Role, error) {
	ret := _m.Called(ctx, role, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Role, []string) (domain.Role, error)); ok {
		return rf(ctx, role, permissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Role, []string) domain.Role); ok {
		r0 = rf(ctx, role, permissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Role, []string) error); ok {
		r1 = rf(ctx, role, permissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RoleUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role domain.Role
//   - permissionIDs []string
func (_e *RoleUsecase_Expecter) Create(ctx interface{}, role interface{}, permissionIDs interface{}) *RoleUsecase_Create_Call {
	return &RoleUsecase_Create_Call{Call: _e.mock.On("Create", ctx, role, permissionIDs)}
}

func (_c *RoleUsecase_Create_Call) Run(run func(ctx context.Context, role domain.Role, permissionIDs []string)) *RoleUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Role), args[2].([]string))
	})
	return _c
}

func (_c *RoleUsecase_Create_Call) Return(_a0 domain.Role, _a1 error) *RoleUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Role, []string) (domain.Role, error)) *RoleUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *RoleUsecase) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RoleUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *RoleUsecase_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *RoleUsecase_Delete_Call {
	return &RoleUsecase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *RoleUsecase_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *RoleUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *RoleUsecase_Delete_Call) Return(_a0 error) *RoleUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleUsecase_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *RoleUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *RoleUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Role, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Role, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Role); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RoleUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *RoleUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *RoleUsecase_Get_Call {
	return &RoleUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *RoleUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *RoleUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RoleUsecase_Get_Call) Return(_a0 domain.Role, _a1 error) *RoleUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Role, error)) *RoleUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *RoleUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Role], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Role]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Role], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Role]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Role])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RoleUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *RoleUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *RoleUsecase_List_Call {
	return &RoleUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *RoleUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *RoleUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RoleUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Role], _a1 error) *RoleUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Role], error)) *RoleUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListComposition provides a mock function with given fields: ctx, roleID
func (_m *RoleUsecase) ListComposition(ctx context.Context, roleID string) ([]domain.RoleComponent, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for ListComposition")
	}

	var r0 []domain.RoleComponent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.RoleComponent, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.RoleComponent); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RoleComponent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_ListComposition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComposition'
type RoleUsecase_ListComposition_Call struct {
	*mock.Call
}

// ListComposition is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
func (_e *RoleUsecase_Expecter) ListComposition(ctx interface{}, roleID interface{}) *RoleUsecase_ListComposition_Call {
	return &RoleUsecase_ListComposition_Call{Call: _e.mock.On("ListComposition", ctx, roleID)}
}

func (_c *RoleUsecase_ListComposition_Call) Run(run func(ctx context.Context, roleID string)) *RoleUsecase_ListComposition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RoleUsecase_ListComposition_Call) Return(_a0 []domain.RoleComponent, _a1 error) *RoleUsecase_ListComposition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_ListComposition_Call) RunAndReturn(run func(context.Context, string) ([]domain.RoleComponent, error)) *RoleUsecase_ListComposition_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function with given fields: ctx, roleID
func (_m *RoleUsecase) ListPermissions(ctx context.Context, roleID string) ([]string, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type RoleUsecase_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
func (_e *RoleUsecase_Expecter) ListPermissions(ctx interface{}, roleID interface{}) *RoleUsecase_ListPermissions_Call {
	return &RoleUsecase_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx, roleID)}
}

func (_c *RoleUsecase_ListPermissions_Call) Run(run func(ctx context.Context, roleID string)) *RoleUsecase_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RoleUsecase_ListPermissions_Call) Return(_a0 []string, _a1 error) *RoleUsecase_ListPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_ListPermissions_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *RoleUsecase_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: _a0, _a1
func (_m *RoleUsecase) Patch(_a0 context.Context, _a1 ...repository.PatchOption) ([]domain.Role, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) ([]domain.Role, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) []domain.Role); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...repository.PatchOption) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleUsecase_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type RoleUsecase_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...repository.PatchOption
func (_e *RoleUsecase_Expecter) Patch(_a0 interface{}, _a1 ...interface{}) *RoleUsecase_Patch_Call {
	return &RoleUsecase_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *RoleUsecase_Patch_Call) Run(run func(_a0 context.Context, _a1 ...repository.PatchOption)) *RoleUsecase_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repository.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(repository.PatchOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RoleUsecase_Patch_Call) Return(_a0 []domain.Role, _a1 error) *RoleUsecase_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoleUsecase_Patch_Call) RunAndReturn(run func(context.Context, ...repository.PatchOption) ([]domain.Role, error)) *RoleUsecase_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// SetComposition provides a mock function with given fields: ctx, roleID, components
func (_m *RoleUsecase) SetComposition(ctx context.Context, roleID string, components []domain.RoleComponent) error {
	ret := _m.Called(ctx, roleID, components)

	if len(ret) == 0 {
		panic("no return value specified for SetComposition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.RoleComponent) error); ok {
		r0 = rf(ctx, roleID, components)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleUsecase_SetComposition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetComposition'
type RoleUsecase_SetComposition_Call struct {
	*mock.Call
}

// SetComposition is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - components []domain.RoleComponent
func (_e *RoleUsecase_Expecter) SetComposition(ctx interface{}, roleID interface{}, components interface{}) *RoleUsecase_SetComposition_Call {
	return &RoleUsecase_SetComposition_Call{Call: _e.mock.On("SetComposition", ctx, roleID, components)}
}

func (_c *RoleUsecase_SetComposition_Call) Run(run func(ctx context.Context, roleID string, components []domain.RoleComponent)) *RoleUsecase_SetComposition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.RoleComponent))
	})
	return _c
}

func (_c *RoleUsecase_SetComposition_Call) Return(_a0 error) *RoleUsecase_SetComposition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleUsecase_SetComposition_Call) RunAndReturn(run func(context.Context, string, []domain.RoleComponent) error) *RoleUsecase_SetComposition_Call {
	_c.Call.Return(run)
	return _c
}

// SetPermissions provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *RoleUsecase) SetPermissions(ctx context.Context, roleID string, permissionIDs []string) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleUsecase_SetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPermissions'
type RoleUsecase_SetPermissions_Call struct {
	*mock.Call
}

// SetPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permissionIDs []string
func (_e *RoleUsecase_Expecter) SetPermissions(ctx interface{}, roleID interface{}, permissionIDs interface{}) *RoleUsecase_SetPermissions_Call {
	return &RoleUsecase_SetPermissions_Call{Call: _e.mock.On("SetPermissions", ctx, roleID, permissionIDs)}
}

func (_c *RoleUsecase_SetPermissions_Call) Run(run func(ctx context.Context, roleID string, permissionIDs []string)) *RoleUsecase_SetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *RoleUsecase_SetPermissions_Call) Return(_a0 error) *RoleUsecase_SetPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleUsecase_SetPermissions_Call) RunAndReturn(run func(context.Context, string, []string) error) *RoleUsecase_SetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewRoleUsecase creates a new instance of RoleUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleUsecase {
	mock := &RoleUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
