// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	domain "github.com/fromforgesoftware/aegis/internal/domain"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// ServiceAccountUsecase is an autogenerated mock type for the ServiceAccountUsecase type
type ServiceAccountUsecase struct {
	mock.Mock
}

type ServiceAccountUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceAccountUsecase) EXPECT() *ServiceAccountUsecase_Expecter {
	return &ServiceAccountUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, realmID, name, scopes
func (_m *ServiceAccountUsecase) Create(ctx context.Context, realmID string, name string, scopes []string) (app.ServiceAccountCredentials, error) {
	ret := _m.Called(ctx, realmID, name, scopes)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 app.ServiceAccountCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (app.ServiceAccountCredentials, error)); ok {
		return rf(ctx, realmID, name, scopes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) app.ServiceAccountCredentials); ok {
		r0 = rf(ctx, realmID, name, scopes)
	} else {
		r0 = ret.Get(0).(app.ServiceAccountCredentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, realmID, name, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ServiceAccountUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - name string
//   - scopes []string
func (_e *ServiceAccountUsecase_Expecter) Create(ctx interface{}, realmID interface{}, name interface{}, scopes interface{}) *ServiceAccountUsecase_Create_Call {
	return &ServiceAccountUsecase_Create_Call{Call: _e.mock.On("Create", ctx, realmID, name, scopes)}
}

func (_c *ServiceAccountUsecase_Create_Call) Run(run func(ctx context.Context, realmID string, name string, scopes []string)) *ServiceAccountUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *ServiceAccountUsecase_Create_Call) Return(_a0 app.ServiceAccountCredentials, _a1 error) *ServiceAccountUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountUsecase_Create_Call) RunAndReturn(run func(context.Context, string, string, []string) (app.ServiceAccountCredentials, error)) *ServiceAccountUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *ServiceAccountUsecase) Delete(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceAccountUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ServiceAccountUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *ServiceAccountUsecase_Expecter) Delete(ctx interface{}, accountID interface{}) *ServiceAccountUsecase_Delete_Call {
	return &ServiceAccountUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, accountID)}
}

func (_c *ServiceAccountUsecase_Delete_Call) Run(run func(ctx context.Context, accountID string)) *ServiceAccountUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ServiceAccountUsecase_Delete_Call) Return(_a0 error) *ServiceAccountUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceAccountUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ServiceAccountUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *ServiceAccountUsecase) Get(ctx context.Context, opts ...search.Option) (domain.ServiceAccount, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.ServiceAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.ServiceAccount, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.ServiceAccount); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.ServiceAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ServiceAccountUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *ServiceAccountUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *ServiceAccountUsecase_Get_Call {
	return &ServiceAccountUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *ServiceAccountUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *ServiceAccountUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ServiceAccountUsecase_Get_Call) Return(_a0 domain.ServiceAccount, _a1 error) *ServiceAccountUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.ServiceAccount, error)) *ServiceAccountUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IssueToken provides a mock function with given fields: ctx, realmID, issuer, clientID, clientSecret
func (_m *ServiceAccountUsecase) IssueToken(ctx context.Context, realmID string, issuer string, clientID string, clientSecret string) (app.TokenResponse, error) {
	ret := _m.Called(ctx, realmID, issuer, clientID, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 app.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (app.TokenResponse, error)); ok {
		return rf(ctx, realmID, issuer, clientID, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) app.TokenResponse); ok {
		r0 = rf(ctx, realmID, issuer, clientID, clientSecret)
	} else {
		r0 = ret.Get(0).(app.TokenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, realmID, issuer, clientID, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountUsecase_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type ServiceAccountUsecase_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - issuer string
//   - clientID string
//   - clientSecret string
func (_e *ServiceAccountUsecase_Expecter) IssueToken(ctx interface{}, realmID interface{}, issuer interface{}, clientID interface{}, clientSecret interface{}) *ServiceAccountUsecase_IssueToken_Call {
	return &ServiceAccountUsecase_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, realmID, issuer, clientID, clientSecret)}
}

func (_c *ServiceAccountUsecase_IssueToken_Call) Run(run func(ctx context.Context, realmID string, issuer string, clientID string, clientSecret string)) *ServiceAccountUsecase_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *ServiceAccountUsecase_IssueToken_Call) Return(_a0 app.TokenResponse, _a1 error) *ServiceAccountUsecase_IssueToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountUsecase_IssueToken_Call) RunAndReturn(run func(context.Context, string, string, string, string) (app.TokenResponse, error)) *ServiceAccountUsecase_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *ServiceAccountUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.ServiceAccount], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.ServiceAccount]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.ServiceAccount], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.ServiceAccount]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.ServiceAccount])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ServiceAccountUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *ServiceAccountUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *ServiceAccountUsecase_List_Call {
	return &ServiceAccountUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *ServiceAccountUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *ServiceAccountUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ServiceAccountUsecase_List_Call) Return(_a0 resource.ListResponse[domain.ServiceAccount], _a1 error) *ServiceAccountUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.ServiceAccount], error)) *ServiceAccountUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceAccountUsecase creates a new instance of ServiceAccountUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAccountUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAccountUsecase {
	mock := &ServiceAccountUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
