// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"

	time "time"
)

// SessionStateUsecase is an autogenerated mock type for the SessionStateUsecase type
type SessionStateUsecase struct {
	mock.Mock
}

type SessionStateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStateUsecase) EXPECT() *SessionStateUsecase_Expecter {
	return &SessionStateUsecase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, opts
func (_m *SessionStateUsecase) Get(ctx context.Context, opts ...search.Option) (domain.SessionState, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.SessionState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.SessionState, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.SessionState); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SessionState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStateUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionStateUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *SessionStateUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *SessionStateUsecase_Get_Call {
	return &SessionStateUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *SessionStateUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *SessionStateUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SessionStateUsecase_Get_Call) Return(_a0 domain.SessionState, _a1 error) *SessionStateUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStateUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.SessionState, error)) *SessionStateUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *SessionStateUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.SessionState], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.SessionState]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.SessionState], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.SessionState]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.SessionState])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStateUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SessionStateUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *SessionStateUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *SessionStateUsecase_List_Call {
	return &SessionStateUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *SessionStateUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *SessionStateUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SessionStateUsecase_List_Call) Return(_a0 resource.ListResponse[domain.SessionState], _a1 error) *SessionStateUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStateUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.SessionState], error)) *SessionStateUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeIdle provides a mock function with given fields: ctx, idleFor
func (_m *SessionStateUsecase) PurgeIdle(ctx context.Context, idleFor time.Duration) (int64, error) {
	ret := _m.Called(ctx, idleFor)

	if len(ret) == 0 {
		panic("no return value specified for PurgeIdle")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (int64, error)); ok {
		return rf(ctx, idleFor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = rf(ctx, idleFor)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, idleFor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStateUsecase_PurgeIdle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeIdle'
type SessionStateUsecase_PurgeIdle_Call struct {
	*mock.Call
}

// PurgeIdle is a helper method to define mock.On call
//   - ctx context.Context
//   - idleFor time.Duration
func (_e *SessionStateUsecase_Expecter) PurgeIdle(ctx interface{}, idleFor interface{}) *SessionStateUsecase_PurgeIdle_Call {
	return &SessionStateUsecase_PurgeIdle_Call{Call: _e.mock.On("PurgeIdle", ctx, idleFor)}
}

func (_c *SessionStateUsecase_PurgeIdle_Call) Run(run func(ctx context.Context, idleFor time.Duration)) *SessionStateUsecase_PurgeIdle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *SessionStateUsecase_PurgeIdle_Call) Return(_a0 int64, _a1 error) *SessionStateUsecase_PurgeIdle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStateUsecase_PurgeIdle_Call) RunAndReturn(run func(context.Context, time.Duration) (int64, error)) *SessionStateUsecase_PurgeIdle_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, sessionID
func (_m *SessionStateUsecase) Touch(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStateUsecase_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type SessionStateUsecase_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SessionStateUsecase_Expecter) Touch(ctx interface{}, sessionID interface{}) *SessionStateUsecase_Touch_Call {
	return &SessionStateUsecase_Touch_Call{Call: _e.mock.On("Touch", ctx, sessionID)}
}

func (_c *SessionStateUsecase_Touch_Call) Run(run func(ctx context.Context, sessionID string)) *SessionStateUsecase_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStateUsecase_Touch_Call) Return(_a0 error) *SessionStateUsecase_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStateUsecase_Touch_Call) RunAndReturn(run func(context.Context, string) error) *SessionStateUsecase_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function with given fields: ctx, s
func (_m *SessionStateUsecase) Track(ctx context.Context, s domain.SessionState) (domain.SessionState, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 domain.SessionState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SessionState) (domain.SessionState, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SessionState) domain.SessionState); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SessionState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SessionState) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStateUsecase_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type SessionStateUsecase_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - ctx context.Context
//   - s domain.SessionState
func (_e *SessionStateUsecase_Expecter) Track(ctx interface{}, s interface{}) *SessionStateUsecase_Track_Call {
	return &SessionStateUsecase_Track_Call{Call: _e.mock.On("Track", ctx, s)}
}

func (_c *SessionStateUsecase_Track_Call) Run(run func(ctx context.Context, s domain.SessionState)) *SessionStateUsecase_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SessionState))
	})
	return _c
}

func (_c *SessionStateUsecase_Track_Call) Return(_a0 domain.SessionState, _a1 error) *SessionStateUsecase_Track_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStateUsecase_Track_Call) RunAndReturn(run func(context.Context, domain.SessionState) (domain.SessionState, error)) *SessionStateUsecase_Track_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionStateUsecase creates a new instance of SessionStateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStateUsecase {
	mock := &SessionStateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
