// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// SigningKeyRepository is an autogenerated mock type for the SigningKeyRepository type
type SigningKeyRepository struct {
	mock.Mock
}

type SigningKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SigningKeyRepository) EXPECT() *SigningKeyRepository_Expecter {
	return &SigningKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SigningKeyRepository) Create(_a0 context.Context, _a1 domain.SigningKey) (domain.SigningKey, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.SigningKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SigningKey) (domain.SigningKey, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SigningKey) domain.SigningKey); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SigningKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SigningKey) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SigningKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.SigningKey
func (_e *SigningKeyRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *SigningKeyRepository_Create_Call {
	return &SigningKeyRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *SigningKeyRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.SigningKey)) *SigningKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SigningKey))
	})
	return _c
}

func (_c *SigningKeyRepository_Create_Call) Return(_a0 domain.SigningKey, _a1 error) *SigningKeyRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyRepository_Create_Call) RunAndReturn(run func(context.Context, domain.SigningKey) (domain.SigningKey, error)) *SigningKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *SigningKeyRepository) Get(ctx context.Context, opts ...search.Option) (domain.SigningKey, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.SigningKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.SigningKey, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.SigningKey); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SigningKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SigningKeyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *SigningKeyRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *SigningKeyRepository_Get_Call {
	return &SigningKeyRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *SigningKeyRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *SigningKeyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SigningKeyRepository_Get_Call) Return(_a0 domain.SigningKey, _a1 error) *SigningKeyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.SigningKey, error)) *SigningKeyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *SigningKeyRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.SigningKey], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.SigningKey]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.SigningKey], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.SigningKey]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.SigningKey])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SigningKeyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *SigningKeyRepository_Expecter) List(ctx interface{}, opts ...interface{}) *SigningKeyRepository_List_Call {
	return &SigningKeyRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *SigningKeyRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *SigningKeyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SigningKeyRepository_List_Call) Return(_a0 resource.ListResponse[domain.SigningKey], _a1 error) *SigningKeyRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.SigningKey], error)) *SigningKeyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewSigningKeyRepository creates a new instance of SigningKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSigningKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SigningKeyRepository {
	mock := &SigningKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
