// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/aegis/internal/app"

	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// SigningKeyService is an autogenerated mock type for the SigningKeyService type
type SigningKeyService struct {
	mock.Mock
}

type SigningKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *SigningKeyService) EXPECT() *SigningKeyService_Expecter {
	return &SigningKeyService_Expecter{mock: &_m.Mock}
}

// ActiveSigner provides a mock function with given fields: ctx, realmID
func (_m *SigningKeyService) ActiveSigner(ctx context.Context, realmID string) (app.Signer, error) {
	ret := _m.Called(ctx, realmID)

	if len(ret) == 0 {
		panic("no return value specified for ActiveSigner")
	}

	var r0 app.Signer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (app.Signer, error)); ok {
		return rf(ctx, realmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) app.Signer); ok {
		r0 = rf(ctx, realmID)
	} else {
		r0 = ret.Get(0).(app.Signer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, realmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyService_ActiveSigner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveSigner'
type SigningKeyService_ActiveSigner_Call struct {
	*mock.Call
}

// ActiveSigner is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
func (_e *SigningKeyService_Expecter) ActiveSigner(ctx interface{}, realmID interface{}) *SigningKeyService_ActiveSigner_Call {
	return &SigningKeyService_ActiveSigner_Call{Call: _e.mock.On("ActiveSigner", ctx, realmID)}
}

func (_c *SigningKeyService_ActiveSigner_Call) Run(run func(ctx context.Context, realmID string)) *SigningKeyService_ActiveSigner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SigningKeyService_ActiveSigner_Call) Return(_a0 app.Signer, _a1 error) *SigningKeyService_ActiveSigner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyService_ActiveSigner_Call) RunAndReturn(run func(context.Context, string) (app.Signer, error)) *SigningKeyService_ActiveSigner_Call {
	_c.Call.Return(run)
	return _c
}

// JWKS provides a mock function with given fields: ctx, realmID
func (_m *SigningKeyService) JWKS(ctx context.Context, realmID string) (json.RawMessage, error) {
	ret := _m.Called(ctx, realmID)

	if len(ret) == 0 {
		panic("no return value specified for JWKS")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (json.RawMessage, error)); ok {
		return rf(ctx, realmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) json.RawMessage); ok {
		r0 = rf(ctx, realmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, realmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyService_JWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWKS'
type SigningKeyService_JWKS_Call struct {
	*mock.Call
}

// JWKS is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
func (_e *SigningKeyService_Expecter) JWKS(ctx interface{}, realmID interface{}) *SigningKeyService_JWKS_Call {
	return &SigningKeyService_JWKS_Call{Call: _e.mock.On("JWKS", ctx, realmID)}
}

func (_c *SigningKeyService_JWKS_Call) Run(run func(ctx context.Context, realmID string)) *SigningKeyService_JWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SigningKeyService_JWKS_Call) Return(_a0 json.RawMessage, _a1 error) *SigningKeyService_JWKS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyService_JWKS_Call) RunAndReturn(run func(context.Context, string) (json.RawMessage, error)) *SigningKeyService_JWKS_Call {
	_c.Call.Return(run)
	return _c
}

// VerificationKey provides a mock function with given fields: ctx, realmID, kid
func (_m *SigningKeyService) VerificationKey(ctx context.Context, realmID string, kid string) (*rsa.PublicKey, error) {
	ret := _m.Called(ctx, realmID, kid)

	if len(ret) == 0 {
		panic("no return value specified for VerificationKey")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*rsa.PublicKey, error)); ok {
		return rf(ctx, realmID, kid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *rsa.PublicKey); ok {
		r0 = rf(ctx, realmID, kid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, realmID, kid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SigningKeyService_VerificationKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerificationKey'
type SigningKeyService_VerificationKey_Call struct {
	*mock.Call
}

// VerificationKey is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - kid string
func (_e *SigningKeyService_Expecter) VerificationKey(ctx interface{}, realmID interface{}, kid interface{}) *SigningKeyService_VerificationKey_Call {
	return &SigningKeyService_VerificationKey_Call{Call: _e.mock.On("VerificationKey", ctx, realmID, kid)}
}

func (_c *SigningKeyService_VerificationKey_Call) Run(run func(ctx context.Context, realmID string, kid string)) *SigningKeyService_VerificationKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SigningKeyService_VerificationKey_Call) Return(_a0 *rsa.PublicKey, _a1 error) *SigningKeyService_VerificationKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SigningKeyService_VerificationKey_Call) RunAndReturn(run func(context.Context, string, string) (*rsa.PublicKey, error)) *SigningKeyService_VerificationKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewSigningKeyService creates a new instance of SigningKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSigningKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SigningKeyService {
	mock := &SigningKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
