// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/aegis/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StepUpTokenRepository is an autogenerated mock type for the StepUpTokenRepository type
type StepUpTokenRepository struct {
	mock.Mock
}

type StepUpTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StepUpTokenRepository) EXPECT() *StepUpTokenRepository_Expecter {
	return &StepUpTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *StepUpTokenRepository) Create(ctx context.Context, t domain.StepUpToken) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StepUpToken) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StepUpTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StepUpTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.StepUpToken
func (_e *StepUpTokenRepository_Expecter) Create(ctx interface{}, t interface{}) *StepUpTokenRepository_Create_Call {
	return &StepUpTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *StepUpTokenRepository_Create_Call) Run(run func(ctx context.Context, t domain.StepUpToken)) *StepUpTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.StepUpToken))
	})
	return _c
}

func (_c *StepUpTokenRepository_Create_Call) Return(_a0 error) *StepUpTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StepUpTokenRepository_Create_Call) RunAndReturn(run func(context.Context, domain.StepUpToken) error) *StepUpTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, id, now
func (_m *StepUpTokenRepository) Verify(ctx context.Context, id string, now time.Time) (domain.StepUpToken, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.StepUpToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.StepUpToken, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.StepUpToken); ok {
		r0 = rf(ctx, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.StepUpToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StepUpTokenRepository_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type StepUpTokenRepository_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - now time.Time
func (_e *StepUpTokenRepository_Expecter) Verify(ctx interface{}, id interface{}, now interface{}) *StepUpTokenRepository_Verify_Call {
	return &StepUpTokenRepository_Verify_Call{Call: _e.mock.On("Verify", ctx, id, now)}
}

func (_c *StepUpTokenRepository_Verify_Call) Run(run func(ctx context.Context, id string, now time.Time)) *StepUpTokenRepository_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *StepUpTokenRepository_Verify_Call) Return(_a0 domain.StepUpToken, _a1 error) *StepUpTokenRepository_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StepUpTokenRepository_Verify_Call) RunAndReturn(run func(context.Context, string, time.Time) (domain.StepUpToken, error)) *StepUpTokenRepository_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewStepUpTokenRepository creates a new instance of StepUpTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStepUpTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StepUpTokenRepository {
	mock := &StepUpTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
