// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VerificationUsecase is an autogenerated mock type for the VerificationUsecase type
type VerificationUsecase struct {
	mock.Mock
}

type VerificationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationUsecase) EXPECT() *VerificationUsecase_Expecter {
	return &VerificationUsecase_Expecter{mock: &_m.Mock}
}

// RequestEmailVerification provides a mock function with given fields: ctx, accountID
func (_m *VerificationUsecase) RequestEmailVerification(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for RequestEmailVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerificationUsecase_RequestEmailVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestEmailVerification'
type VerificationUsecase_RequestEmailVerification_Call struct {
	*mock.Call
}

// RequestEmailVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *VerificationUsecase_Expecter) RequestEmailVerification(ctx interface{}, accountID interface{}) *VerificationUsecase_RequestEmailVerification_Call {
	return &VerificationUsecase_RequestEmailVerification_Call{Call: _e.mock.On("RequestEmailVerification", ctx, accountID)}
}

func (_c *VerificationUsecase_RequestEmailVerification_Call) Run(run func(ctx context.Context, accountID string)) *VerificationUsecase_RequestEmailVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VerificationUsecase_RequestEmailVerification_Call) Return(_a0 error) *VerificationUsecase_RequestEmailVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerificationUsecase_RequestEmailVerification_Call) RunAndReturn(run func(context.Context, string) error) *VerificationUsecase_RequestEmailVerification_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, token
func (_m *VerificationUsecase) VerifyEmail(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerificationUsecase_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type VerificationUsecase_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *VerificationUsecase_Expecter) VerifyEmail(ctx interface{}, token interface{}) *VerificationUsecase_VerifyEmail_Call {
	return &VerificationUsecase_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *VerificationUsecase_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *VerificationUsecase_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VerificationUsecase_VerifyEmail_Call) Return(_a0 error) *VerificationUsecase_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerificationUsecase_VerifyEmail_Call) RunAndReturn(run func(context.Context, string) error) *VerificationUsecase_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerificationUsecase creates a new instance of VerificationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationUsecase {
	mock := &VerificationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
