// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// VerificationTokenRepository is an autogenerated mock type for the VerificationTokenRepository type
type VerificationTokenRepository struct {
	mock.Mock
}

type VerificationTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationTokenRepository) EXPECT() *VerificationTokenRepository_Expecter {
	return &VerificationTokenRepository_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, tokenHash, now
func (_m *VerificationTokenRepository) Consume(ctx context.Context, tokenHash string, now time.Time) (string, error) {
	ret := _m.Called(ctx, tokenHash, now)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (string, error)); ok {
		return rf(ctx, tokenHash, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) string); ok {
		r0 = rf(ctx, tokenHash, now)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, tokenHash, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerificationTokenRepository_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type VerificationTokenRepository_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - now time.Time
func (_e *VerificationTokenRepository_Expecter) Consume(ctx interface{}, tokenHash interface{}, now interface{}) *VerificationTokenRepository_Consume_Call {
	return &VerificationTokenRepository_Consume_Call{Call: _e.mock.On("Consume", ctx, tokenHash, now)}
}

func (_c *VerificationTokenRepository_Consume_Call) Run(run func(ctx context.Context, tokenHash string, now time.Time)) *VerificationTokenRepository_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *VerificationTokenRepository_Consume_Call) Return(accountID string, err error) *VerificationTokenRepository_Consume_Call {
	_c.Call.Return(accountID, err)
	return _c
}

func (_c *VerificationTokenRepository_Consume_Call) RunAndReturn(run func(context.Context, string, time.Time) (string, error)) *VerificationTokenRepository_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, accountID, tokenHash, expiresAt
func (_m *VerificationTokenRepository) Create(ctx context.Context, accountID string, tokenHash string, expiresAt time.Time) error {
	ret := _m.Called(ctx, accountID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, accountID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerificationTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VerificationTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *VerificationTokenRepository_Expecter) Create(ctx interface{}, accountID interface{}, tokenHash interface{}, expiresAt interface{}) *VerificationTokenRepository_Create_Call {
	return &VerificationTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, accountID, tokenHash, expiresAt)}
}

func (_c *VerificationTokenRepository_Create_Call) Run(run func(ctx context.Context, accountID string, tokenHash string, expiresAt time.Time)) *VerificationTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *VerificationTokenRepository_Create_Call) Return(_a0 error) *VerificationTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerificationTokenRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *VerificationTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerificationTokenRepository creates a new instance of VerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationTokenRepository {
	mock := &VerificationTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
