// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/admin.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_aegis_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_admin_proto_rawDescGZIP(), []int{0}
}

type HealthzResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is "SERVING" when the service is ready to accept traffic.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// version is the running service version (matches the image tag).
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_aegis_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthzResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_aegis_v1_admin_proto protoreflect.FileDescriptor

const file_aegis_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v1/admin.proto\x12\baegis.v1\"\x10\n" +
	"\x0eHealthzRequest\"C\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2N\n" +
	"\fAdminService\x12>\n" +
	"\aHealthz\x12\x18.aegis.v1.HealthzRequest\x1a\x19.aegis.v1.HealthzResponseB\x98\x01\n" +
	"\fcom.aegis.v1B\n" +
	"AdminProtoP\x01Z;github.com/fromforgesoftware/aegis/pkg/api/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_admin_proto_rawDescOnce sync.Once
	file_aegis_v1_admin_proto_rawDescData []byte
)

func file_aegis_v1_admin_proto_rawDescGZIP() []byte {
	file_aegis_v1_admin_proto_rawDescOnce.Do(func() {
		file_aegis_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_admin_proto_rawDesc), len(file_aegis_v1_admin_proto_rawDesc)))
	})
	return file_aegis_v1_admin_proto_rawDescData
}

var file_aegis_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aegis_v1_admin_proto_goTypes = []any{
	(*HealthzRequest)(nil),  // 0: aegis.v1.HealthzRequest
	(*HealthzResponse)(nil), // 1: aegis.v1.HealthzResponse
}
var file_aegis_v1_admin_proto_depIdxs = []int32{
	0, // 0: aegis.v1.AdminService.Healthz:input_type -> aegis.v1.HealthzRequest
	1, // 1: aegis.v1.AdminService.Healthz:output_type -> aegis.v1.HealthzResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aegis_v1_admin_proto_init() }
func file_aegis_v1_admin_proto_init() {
	if File_aegis_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_admin_proto_rawDesc), len(file_aegis_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_admin_proto_goTypes,
		DependencyIndexes: file_aegis_v1_admin_proto_depIdxs,
		MessageInfos:      file_aegis_v1_admin_proto_msgTypes,
	}.Build()
	File_aegis_v1_admin_proto = out.File
	file_aegis_v1_admin_proto_goTypes = nil
	file_aegis_v1_admin_proto_depIdxs = nil
}
