// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/authorization.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	MinVersion    int64                  `protobuf:"varint,4,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *CheckRequest) GetMinVersion() int64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{2}
}

type VersionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WriteVersion      int64                  `protobuf:"varint,1,opt,name=write_version,json=writeVersion,proto3" json:"write_version,omitempty"`
	ProjectionVersion int64                  `protobuf:"varint,2,opt,name=projection_version,json=projectionVersion,proto3" json:"projection_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetWriteVersion() int64 {
	if x != nil {
		return x.WriteVersion
	}
	return 0
}

func (x *VersionResponse) GetProjectionVersion() int64 {
	if x != nil {
		return x.ProjectionVersion
	}
	return 0
}

type PermissionCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionCheck) Reset() {
	*x = PermissionCheck{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionCheck) ProtoMessage() {}

func (x *PermissionCheck) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionCheck.ProtoReflect.Descriptor instead.
func (*PermissionCheck) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionCheck) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PermissionCheck) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type PermissionDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Allowed       bool                   `protobuf:"varint,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDecision) Reset() {
	*x = PermissionDecision{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDecision) ProtoMessage() {}

func (x *PermissionDecision) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDecision.ProtoReflect.Descriptor instead.
func (*PermissionDecision) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionDecision) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PermissionDecision) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *PermissionDecision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Checks        []*PermissionCheck     `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	MinVersion    int64                  `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCheckRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BatchCheckRequest) GetChecks() []*PermissionCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *BatchCheckRequest) GetMinVersion() int64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*PermissionDecision  `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCheckResponse) GetDecisions() []*PermissionDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type ListAccessibleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	MinVersion    int64                  `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessibleRequest) Reset() {
	*x = ListAccessibleRequest{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleRequest) ProtoMessage() {}

func (x *ListAccessibleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleRequest.ProtoReflect.Descriptor instead.
func (*ListAccessibleRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccessibleRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListAccessibleRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *ListAccessibleRequest) GetMinVersion() int64 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

type ListAccessibleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceIds   []string               `protobuf:"bytes,1,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessibleResponse) Reset() {
	*x = ListAccessibleResponse{}
	mi := &file_aegis_v1_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleResponse) ProtoMessage() {}

func (x *ListAccessibleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleResponse.ProtoReflect.Descriptor instead.
func (*ListAccessibleResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccessibleResponse) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

var File_aegis_v1_authorization_proto protoreflect.FileDescriptor

const file_aegis_v1_authorization_proto_rawDesc = "" +
	"\n" +
	"\x1caegis/v1/authorization.proto\x12\baegis.v1\"\x94\x01\n" +
	"\fCheckRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\tR\fpermissionId\x12\x1f\n" +
	"\vmin_version\x18\x04 \x01(\x03R\n" +
	"minVersion\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"\x10\n" +
	"\x0eVersionRequest\"e\n" +
	"\x0fVersionResponse\x12#\n" +
	"\rwrite_version\x18\x01 \x01(\x03R\fwriteVersion\x12-\n" +
	"\x12projection_version\x18\x02 \x01(\x03R\x11projectionVersion\"W\n" +
	"\x0fPermissionCheck\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\"t\n" +
	"\x12PermissionDecision\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12\x18\n" +
	"\aallowed\x18\x03 \x01(\bR\aallowed\"\x86\x01\n" +
	"\x11BatchCheckRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x121\n" +
	"\x06checks\x18\x02 \x03(\v2\x19.aegis.v1.PermissionCheckR\x06checks\x12\x1f\n" +
	"\vmin_version\x18\x03 \x01(\x03R\n" +
	"minVersion\"P\n" +
	"\x12BatchCheckResponse\x12:\n" +
	"\tdecisions\x18\x01 \x03(\v2\x1c.aegis.v1.PermissionDecisionR\tdecisions\"|\n" +
	"\x15ListAccessibleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12\x1f\n" +
	"\vmin_version\x18\x03 \x01(\x03R\n" +
	"minVersion\";\n" +
	"\x16ListAccessibleResponse\x12!\n" +
	"\fresource_ids\x18\x01 \x03(\tR\vresourceIds2\xab\x02\n" +
	"\x11AuthorizerService\x128\n" +
	"\x05Check\x12\x16.aegis.v1.CheckRequest\x1a\x17.aegis.v1.CheckResponse\x12G\n" +
	"\n" +
	"BatchCheck\x12\x1b.aegis.v1.BatchCheckRequest\x1a\x1c.aegis.v1.BatchCheckResponse\x12S\n" +
	"\x0eListAccessible\x12\x1f.aegis.v1.ListAccessibleRequest\x1a .aegis.v1.ListAccessibleResponse\x12>\n" +
	"\aVersion\x12\x18.aegis.v1.VersionRequest\x1a\x19.aegis.v1.VersionResponseB\xa0\x01\n" +
	"\fcom.aegis.v1B\x12AuthorizationProtoP\x01Z;github.com/fromforgesoftware/aegis/pkg/api/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_authorization_proto_rawDescOnce sync.Once
	file_aegis_v1_authorization_proto_rawDescData []byte
)

func file_aegis_v1_authorization_proto_rawDescGZIP() []byte {
	file_aegis_v1_authorization_proto_rawDescOnce.Do(func() {
		file_aegis_v1_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_authorization_proto_rawDesc), len(file_aegis_v1_authorization_proto_rawDesc)))
	})
	return file_aegis_v1_authorization_proto_rawDescData
}

var file_aegis_v1_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aegis_v1_authorization_proto_goTypes = []any{
	(*CheckRequest)(nil),           // 0: aegis.v1.CheckRequest
	(*CheckResponse)(nil),          // 1: aegis.v1.CheckResponse
	(*VersionRequest)(nil),         // 2: aegis.v1.VersionRequest
	(*VersionResponse)(nil),        // 3: aegis.v1.VersionResponse
	(*PermissionCheck)(nil),        // 4: aegis.v1.PermissionCheck
	(*PermissionDecision)(nil),     // 5: aegis.v1.PermissionDecision
	(*BatchCheckRequest)(nil),      // 6: aegis.v1.BatchCheckRequest
	(*BatchCheckResponse)(nil),     // 7: aegis.v1.BatchCheckResponse
	(*ListAccessibleRequest)(nil),  // 8: aegis.v1.ListAccessibleRequest
	(*ListAccessibleResponse)(nil), // 9: aegis.v1.ListAccessibleResponse
}
var file_aegis_v1_authorization_proto_depIdxs = []int32{
	4, // 0: aegis.v1.BatchCheckRequest.checks:type_name -> aegis.v1.PermissionCheck
	5, // 1: aegis.v1.BatchCheckResponse.decisions:type_name -> aegis.v1.PermissionDecision
	0, // 2: aegis.v1.AuthorizerService.Check:input_type -> aegis.v1.CheckRequest
	6, // 3: aegis.v1.AuthorizerService.BatchCheck:input_type -> aegis.v1.BatchCheckRequest
	8, // 4: aegis.v1.AuthorizerService.ListAccessible:input_type -> aegis.v1.ListAccessibleRequest
	2, // 5: aegis.v1.AuthorizerService.Version:input_type -> aegis.v1.VersionRequest
	1, // 6: aegis.v1.AuthorizerService.Check:output_type -> aegis.v1.CheckResponse
	7, // 7: aegis.v1.AuthorizerService.BatchCheck:output_type -> aegis.v1.BatchCheckResponse
	9, // 8: aegis.v1.AuthorizerService.ListAccessible:output_type -> aegis.v1.ListAccessibleResponse
	3, // 9: aegis.v1.AuthorizerService.Version:output_type -> aegis.v1.VersionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aegis_v1_authorization_proto_init() }
func file_aegis_v1_authorization_proto_init() {
	if File_aegis_v1_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_authorization_proto_rawDesc), len(file_aegis_v1_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_authorization_proto_goTypes,
		DependencyIndexes: file_aegis_v1_authorization_proto_depIdxs,
		MessageInfos:      file_aegis_v1_authorization_proto_msgTypes,
	}.Build()
	File_aegis_v1_authorization_proto = out.File
	file_aegis_v1_authorization_proto_goTypes = nil
	file_aegis_v1_authorization_proto_depIdxs = nil
}
