// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/authx.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RequestEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationRequest) Reset() {
	*x = RequestEmailVerificationRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationRequest) ProtoMessage() {}

func (x *RequestEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{4}
}

func (x *RequestEmailVerificationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RequestEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationResponse) Reset() {
	*x = RequestEmailVerificationResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationResponse) ProtoMessage() {}

func (x *RequestEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{5}
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{7}
}

type RequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{8}
}

func (x *RequestPasswordResetRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RequestPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RequestPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetResponse) Reset() {
	*x = RequestPasswordResetResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetResponse) ProtoMessage() {}

func (x *RequestPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{9}
}

type ConfirmPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPasswordResetRequest) Reset() {
	*x = ConfirmPasswordResetRequest{}
	mi := &file_aegis_v1_authx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPasswordResetRequest) ProtoMessage() {}

func (x *ConfirmPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmPasswordResetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfirmPasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ConfirmPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPasswordResetResponse) Reset() {
	*x = ConfirmPasswordResetResponse{}
	mi := &file_aegis_v1_authx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPasswordResetResponse) ProtoMessage() {}

func (x *ConfirmPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{11}
}

// Account is the authenticated identity projection returned by the auth
// surface. The password hash is never exposed.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RealmId       string                 `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`     // USER | SERVICE
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // CREATED | ENABLED | DISABLED | BANNED
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	DisplayName   string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_aegis_v1_authx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authx_proto_rawDescGZIP(), []int{12}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *Account) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

var File_aegis_v1_authx_proto protoreflect.FileDescriptor

const file_aegis_v1_authx_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v1/authx.proto\x12\baegis.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"?\n" +
	"\x10RegisterResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.aegis.v1.AccountR\aaccount\"[\n" +
	"\fLoginRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"<\n" +
	"\rLoginResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.aegis.v1.AccountR\aaccount\"@\n" +
	"\x1fRequestEmailVerificationRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\"\n" +
	" RequestEmailVerificationResponse\"*\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x15\n" +
	"\x13VerifyEmailResponse\"N\n" +
	"\x1bRequestPasswordResetRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x1e\n" +
	"\x1cRequestPasswordResetResponse\"V\n" +
	"\x1bConfirmPasswordResetRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x1e\n" +
	"\x1cConfirmPasswordResetResponse\"\xbb\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x06 \x01(\bR\remailVerified\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\rlast_login_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt2\x98\x04\n" +
	"\fAuthxService\x12A\n" +
	"\bRegister\x12\x19.aegis.v1.RegisterRequest\x1a\x1a.aegis.v1.RegisterResponse\x128\n" +
	"\x05Login\x12\x16.aegis.v1.LoginRequest\x1a\x17.aegis.v1.LoginResponse\x12q\n" +
	"\x18RequestEmailVerification\x12).aegis.v1.RequestEmailVerificationRequest\x1a*.aegis.v1.RequestEmailVerificationResponse\x12J\n" +
	"\vVerifyEmail\x12\x1c.aegis.v1.VerifyEmailRequest\x1a\x1d.aegis.v1.VerifyEmailResponse\x12e\n" +
	"\x14RequestPasswordReset\x12%.aegis.v1.RequestPasswordResetRequest\x1a&.aegis.v1.RequestPasswordResetResponse\x12e\n" +
	"\x14ConfirmPasswordReset\x12%.aegis.v1.ConfirmPasswordResetRequest\x1a&.aegis.v1.ConfirmPasswordResetResponseB\x98\x01\n" +
	"\fcom.aegis.v1B\n" +
	"AuthxProtoP\x01Z;github.com/fromforgesoftware/aegis/pkg/api/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_authx_proto_rawDescOnce sync.Once
	file_aegis_v1_authx_proto_rawDescData []byte
)

func file_aegis_v1_authx_proto_rawDescGZIP() []byte {
	file_aegis_v1_authx_proto_rawDescOnce.Do(func() {
		file_aegis_v1_authx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_authx_proto_rawDesc), len(file_aegis_v1_authx_proto_rawDesc)))
	})
	return file_aegis_v1_authx_proto_rawDescData
}

var file_aegis_v1_authx_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_aegis_v1_authx_proto_goTypes = []any{
	(*RegisterRequest)(nil),                  // 0: aegis.v1.RegisterRequest
	(*RegisterResponse)(nil),                 // 1: aegis.v1.RegisterResponse
	(*LoginRequest)(nil),                     // 2: aegis.v1.LoginRequest
	(*LoginResponse)(nil),                    // 3: aegis.v1.LoginResponse
	(*RequestEmailVerificationRequest)(nil),  // 4: aegis.v1.RequestEmailVerificationRequest
	(*RequestEmailVerificationResponse)(nil), // 5: aegis.v1.RequestEmailVerificationResponse
	(*VerifyEmailRequest)(nil),               // 6: aegis.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),              // 7: aegis.v1.VerifyEmailResponse
	(*RequestPasswordResetRequest)(nil),      // 8: aegis.v1.RequestPasswordResetRequest
	(*RequestPasswordResetResponse)(nil),     // 9: aegis.v1.RequestPasswordResetResponse
	(*ConfirmPasswordResetRequest)(nil),      // 10: aegis.v1.ConfirmPasswordResetRequest
	(*ConfirmPasswordResetResponse)(nil),     // 11: aegis.v1.ConfirmPasswordResetResponse
	(*Account)(nil),                          // 12: aegis.v1.Account
	(*timestamppb.Timestamp)(nil),            // 13: google.protobuf.Timestamp
}
var file_aegis_v1_authx_proto_depIdxs = []int32{
	12, // 0: aegis.v1.RegisterResponse.account:type_name -> aegis.v1.Account
	12, // 1: aegis.v1.LoginResponse.account:type_name -> aegis.v1.Account
	13, // 2: aegis.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: aegis.v1.Account.last_login_at:type_name -> google.protobuf.Timestamp
	0,  // 4: aegis.v1.AuthxService.Register:input_type -> aegis.v1.RegisterRequest
	2,  // 5: aegis.v1.AuthxService.Login:input_type -> aegis.v1.LoginRequest
	4,  // 6: aegis.v1.AuthxService.RequestEmailVerification:input_type -> aegis.v1.RequestEmailVerificationRequest
	6,  // 7: aegis.v1.AuthxService.VerifyEmail:input_type -> aegis.v1.VerifyEmailRequest
	8,  // 8: aegis.v1.AuthxService.RequestPasswordReset:input_type -> aegis.v1.RequestPasswordResetRequest
	10, // 9: aegis.v1.AuthxService.ConfirmPasswordReset:input_type -> aegis.v1.ConfirmPasswordResetRequest
	1,  // 10: aegis.v1.AuthxService.Register:output_type -> aegis.v1.RegisterResponse
	3,  // 11: aegis.v1.AuthxService.Login:output_type -> aegis.v1.LoginResponse
	5,  // 12: aegis.v1.AuthxService.RequestEmailVerification:output_type -> aegis.v1.RequestEmailVerificationResponse
	7,  // 13: aegis.v1.AuthxService.VerifyEmail:output_type -> aegis.v1.VerifyEmailResponse
	9,  // 14: aegis.v1.AuthxService.RequestPasswordReset:output_type -> aegis.v1.RequestPasswordResetResponse
	11, // 15: aegis.v1.AuthxService.ConfirmPasswordReset:output_type -> aegis.v1.ConfirmPasswordResetResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_aegis_v1_authx_proto_init() }
func file_aegis_v1_authx_proto_init() {
	if File_aegis_v1_authx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_authx_proto_rawDesc), len(file_aegis_v1_authx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_authx_proto_goTypes,
		DependencyIndexes: file_aegis_v1_authx_proto_depIdxs,
		MessageInfos:      file_aegis_v1_authx_proto_msgTypes,
	}.Build()
	File_aegis_v1_authx_proto = out.File
	file_aegis_v1_authx_proto_goTypes = nil
	file_aegis_v1_authx_proto_depIdxs = nil
}
