// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/identity_broker.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	IdpName       string                 `protobuf:"bytes,2,opt,name=idp_name,json=idpName,proto3" json:"idp_name,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountRequest) Reset() {
	*x = ResolveAccountRequest{}
	mi := &file_aegis_v1_identity_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountRequest) ProtoMessage() {}

func (x *ResolveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_identity_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountRequest.ProtoReflect.Descriptor instead.
func (*ResolveAccountRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_identity_broker_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveAccountRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *ResolveAccountRequest) GetIdpName() string {
	if x != nil {
		return x.IdpName
	}
	return ""
}

func (x *ResolveAccountRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResolveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Created       bool                   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	LinkRequired  bool                   `protobuf:"varint,5,opt,name=link_required,json=linkRequired,proto3" json:"link_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountResponse) Reset() {
	*x = ResolveAccountResponse{}
	mi := &file_aegis_v1_identity_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountResponse) ProtoMessage() {}

func (x *ResolveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_identity_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountResponse.ProtoReflect.Descriptor instead.
func (*ResolveAccountResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_identity_broker_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ResolveAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResolveAccountResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResolveAccountResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *ResolveAccountResponse) GetLinkRequired() bool {
	if x != nil {
		return x.LinkRequired
	}
	return false
}

var File_aegis_v1_identity_broker_proto protoreflect.FileDescriptor

const file_aegis_v1_identity_broker_proto_rawDesc = "" +
	"\n" +
	"\x1eaegis/v1/identity_broker.proto\x12\baegis.v1\"c\n" +
	"\x15ResolveAccountRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x19\n" +
	"\bidp_name\x18\x02 \x01(\tR\aidpName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xaf\x01\n" +
	"\x16ResolveAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acreated\x18\x04 \x01(\bR\acreated\x12#\n" +
	"\rlink_required\x18\x05 \x01(\bR\flinkRequired2l\n" +
	"\x15IdentityBrokerService\x12S\n" +
	"\x0eResolveAccount\x12\x1f.aegis.v1.ResolveAccountRequest\x1a .aegis.v1.ResolveAccountResponseB\xa1\x01\n" +
	"\fcom.aegis.v1B\x13IdentityBrokerProtoP\x01Z;github.com/fromforgesoftware/aegis/pkg/api/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_identity_broker_proto_rawDescOnce sync.Once
	file_aegis_v1_identity_broker_proto_rawDescData []byte
)

func file_aegis_v1_identity_broker_proto_rawDescGZIP() []byte {
	file_aegis_v1_identity_broker_proto_rawDescOnce.Do(func() {
		file_aegis_v1_identity_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_identity_broker_proto_rawDesc), len(file_aegis_v1_identity_broker_proto_rawDesc)))
	})
	return file_aegis_v1_identity_broker_proto_rawDescData
}

var file_aegis_v1_identity_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aegis_v1_identity_broker_proto_goTypes = []any{
	(*ResolveAccountRequest)(nil),  // 0: aegis.v1.ResolveAccountRequest
	(*ResolveAccountResponse)(nil), // 1: aegis.v1.ResolveAccountResponse
}
var file_aegis_v1_identity_broker_proto_depIdxs = []int32{
	0, // 0: aegis.v1.IdentityBrokerService.ResolveAccount:input_type -> aegis.v1.ResolveAccountRequest
	1, // 1: aegis.v1.IdentityBrokerService.ResolveAccount:output_type -> aegis.v1.ResolveAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aegis_v1_identity_broker_proto_init() }
func file_aegis_v1_identity_broker_proto_init() {
	if File_aegis_v1_identity_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_identity_broker_proto_rawDesc), len(file_aegis_v1_identity_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_identity_broker_proto_goTypes,
		DependencyIndexes: file_aegis_v1_identity_broker_proto_depIdxs,
		MessageInfos:      file_aegis_v1_identity_broker_proto_msgTypes,
	}.Build()
	File_aegis_v1_identity_broker_proto = out.File
	file_aegis_v1_identity_broker_proto_goTypes = nil
	file_aegis_v1_identity_broker_proto_depIdxs = nil
}
