// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: aegis/v1/identity_broker.proto

package aegisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityBrokerService_ResolveAccount_FullMethodName = "/aegis.v1.IdentityBrokerService/ResolveAccount"
)

// IdentityBrokerServiceClient is the client API for IdentityBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityBrokerService is the low-latency S2S surface for federation. The
// hot path — verify upstream token → resolve account — runs through gRPC so
// service-to-service callers (mmo-game's auth gateway, trading-bot's edge)
// can skip the JSON:API parsing tax.
type IdentityBrokerServiceClient interface {
	// ResolveAccount verifies the raw upstream token against the named realm's
	// IdP config and resolves (or JIT-provisions) the matching Aegis account.
	ResolveAccount(ctx context.Context, in *ResolveAccountRequest, opts ...grpc.CallOption) (*ResolveAccountResponse, error)
}

type identityBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityBrokerServiceClient(cc grpc.ClientConnInterface) IdentityBrokerServiceClient {
	return &identityBrokerServiceClient{cc}
}

func (c *identityBrokerServiceClient) ResolveAccount(ctx context.Context, in *ResolveAccountRequest, opts ...grpc.CallOption) (*ResolveAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAccountResponse)
	err := c.cc.Invoke(ctx, IdentityBrokerService_ResolveAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityBrokerServiceServer is the server API for IdentityBrokerService service.
// All implementations should embed UnimplementedIdentityBrokerServiceServer
// for forward compatibility.
//
// IdentityBrokerService is the low-latency S2S surface for federation. The
// hot path — verify upstream token → resolve account — runs through gRPC so
// service-to-service callers (mmo-game's auth gateway, trading-bot's edge)
// can skip the JSON:API parsing tax.
type IdentityBrokerServiceServer interface {
	// ResolveAccount verifies the raw upstream token against the named realm's
	// IdP config and resolves (or JIT-provisions) the matching Aegis account.
	ResolveAccount(context.Context, *ResolveAccountRequest) (*ResolveAccountResponse, error)
}

// UnimplementedIdentityBrokerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityBrokerServiceServer struct{}

func (UnimplementedIdentityBrokerServiceServer) ResolveAccount(context.Context, *ResolveAccountRequest) (*ResolveAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAccount not implemented")
}
func (UnimplementedIdentityBrokerServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityBrokerServiceServer will
// result in compilation errors.
type UnsafeIdentityBrokerServiceServer interface {
	mustEmbedUnimplementedIdentityBrokerServiceServer()
}

func RegisterIdentityBrokerServiceServer(s grpc.ServiceRegistrar, srv IdentityBrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityBrokerService_ServiceDesc, srv)
}

func _IdentityBrokerService_ResolveAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBrokerServiceServer).ResolveAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBrokerService_ResolveAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBrokerServiceServer).ResolveAccount(ctx, req.(*ResolveAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityBrokerService_ServiceDesc is the grpc.ServiceDesc for IdentityBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v1.IdentityBrokerService",
	HandlerType: (*IdentityBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveAccount",
			Handler:    _IdentityBrokerService_ResolveAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aegis/v1/identity_broker.proto",
}
