// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/oauth.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RefreshRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *RefreshRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IdToken       string                 `protobuf:"bytes,5,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	Scope         string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *TokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type IntrospectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	TokenTypeHint string                 `protobuf:"bytes,5,opt,name=token_type_hint,json=tokenTypeHint,proto3" json:"token_type_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *IntrospectRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *IntrospectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IntrospectRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IntrospectRequest) GetTokenTypeHint() string {
	if x != nil {
		return x.TokenTypeHint
	}
	return ""
}

type IntrospectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sub           string                 `protobuf:"bytes,4,opt,name=sub,proto3" json:"sub,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Exp           int64                  `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	Iat           int64                  `protobuf:"varint,7,opt,name=iat,proto3" json:"iat,omitempty"`
	Aud           string                 `protobuf:"bytes,8,opt,name=aud,proto3" json:"aud,omitempty"`
	Iss           string                 `protobuf:"bytes,9,opt,name=iss,proto3" json:"iss,omitempty"`
	OrgId         string                 `protobuf:"bytes,10,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgRole       string                 `protobuf:"bytes,11,opt,name=org_role,json=orgRole,proto3" json:"org_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *IntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IntrospectResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IntrospectResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *IntrospectResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *IntrospectResponse) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *IntrospectResponse) GetIat() int64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *IntrospectResponse) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *IntrospectResponse) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *IntrospectResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *IntrospectResponse) GetOrgRole() string {
	if x != nil {
		return x.OrgRole
	}
	return ""
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	TokenTypeHint string                 `protobuf:"bytes,5,opt,name=token_type_hint,json=tokenTypeHint,proto3" json:"token_type_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RevokeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RevokeRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *RevokeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RevokeRequest) GetTokenTypeHint() string {
	if x != nil {
		return x.TokenTypeHint
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_aegis_v1_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_oauth_proto_rawDescGZIP(), []int{5}
}

var File_aegis_v1_oauth_proto protoreflect.FileDescriptor

const file_aegis_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v1/oauth.proto\x12\baegis.v1\"\xaa\x01\n" +
	"\x0eRefreshRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x04 \x01(\tR\fclientSecret\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\"\xc6\x01\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x19\n" +
	"\bid_token\x18\x05 \x01(\tR\aidToken\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\"\xae\x01\n" +
	"\x11IntrospectRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x05 \x01(\tR\rtokenTypeHint\"\x8a\x02\n" +
	"\x12IntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03sub\x18\x04 \x01(\tR\x03sub\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x10\n" +
	"\x03exp\x18\x06 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03iat\x18\a \x01(\x03R\x03iat\x12\x10\n" +
	"\x03aud\x18\b \x01(\tR\x03aud\x12\x10\n" +
	"\x03iss\x18\t \x01(\tR\x03iss\x12\x15\n" +
	"\x06org_id\x18\n" +
	" \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_role\x18\v \x01(\tR\aorgRole\"\xaa\x01\n" +
	"\rRevokeRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x05 \x01(\tR\rtokenTypeHint\"\x10\n" +
	"\x0eRevokeResponse2\xd2\x01\n" +
	"\fOAuthService\x12<\n" +
	"\aRefresh\x12\x18.aegis.v1.RefreshRequest\x1a\x17.aegis.v1.TokenResponse\x12G\n" +
	"\n" +
	"Introspect\x12\x1b.aegis.v1.IntrospectRequest\x1a\x1c.aegis.v1.IntrospectResponse\x12;\n" +
	"\x06Revoke\x12\x17.aegis.v1.RevokeRequest\x1a\x18.aegis.v1.RevokeResponseB\x98\x01\n" +
	"\fcom.aegis.v1B\n" +
	"OauthProtoP\x01Z;github.com/fromforgesoftware/aegis/pkg/api/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_oauth_proto_rawDescOnce sync.Once
	file_aegis_v1_oauth_proto_rawDescData []byte
)

func file_aegis_v1_oauth_proto_rawDescGZIP() []byte {
	file_aegis_v1_oauth_proto_rawDescOnce.Do(func() {
		file_aegis_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_oauth_proto_rawDesc), len(file_aegis_v1_oauth_proto_rawDesc)))
	})
	return file_aegis_v1_oauth_proto_rawDescData
}

var file_aegis_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aegis_v1_oauth_proto_goTypes = []any{
	(*RefreshRequest)(nil),     // 0: aegis.v1.RefreshRequest
	(*TokenResponse)(nil),      // 1: aegis.v1.TokenResponse
	(*IntrospectRequest)(nil),  // 2: aegis.v1.IntrospectRequest
	(*IntrospectResponse)(nil), // 3: aegis.v1.IntrospectResponse
	(*RevokeRequest)(nil),      // 4: aegis.v1.RevokeRequest
	(*RevokeResponse)(nil),     // 5: aegis.v1.RevokeResponse
}
var file_aegis_v1_oauth_proto_depIdxs = []int32{
	0, // 0: aegis.v1.OAuthService.Refresh:input_type -> aegis.v1.RefreshRequest
	2, // 1: aegis.v1.OAuthService.Introspect:input_type -> aegis.v1.IntrospectRequest
	4, // 2: aegis.v1.OAuthService.Revoke:input_type -> aegis.v1.RevokeRequest
	1, // 3: aegis.v1.OAuthService.Refresh:output_type -> aegis.v1.TokenResponse
	3, // 4: aegis.v1.OAuthService.Introspect:output_type -> aegis.v1.IntrospectResponse
	5, // 5: aegis.v1.OAuthService.Revoke:output_type -> aegis.v1.RevokeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aegis_v1_oauth_proto_init() }
func file_aegis_v1_oauth_proto_init() {
	if File_aegis_v1_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_oauth_proto_rawDesc), len(file_aegis_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_oauth_proto_goTypes,
		DependencyIndexes: file_aegis_v1_oauth_proto_depIdxs,
		MessageInfos:      file_aegis_v1_oauth_proto_msgTypes,
	}.Build()
	File_aegis_v1_oauth_proto = out.File
	file_aegis_v1_oauth_proto_goTypes = nil
	file_aegis_v1_oauth_proto_depIdxs = nil
}
